import os

target_dir = "/home/thinh/Documents/Obsidian Vault/English/Vocabulary Topics/4. Places & Travel/VACATION"
os.makedirs(target_dir, exist_ok=True)
topic = "VACATION"

words = [
    # A1-A2 (15)
    ["Beach", "Noun", "/biːtʃ/", "A1-A2", "Daily", "An area of sand or stones next to the sea.", "Bãi biển", "Beach nghe giống Bích, Bích rất thích đi biển chơi.", ["go to the beach: đi biển", "sandy beach: bãi biển cát"], "We spent all day at the beach.", "Chúng tôi dành cả ngày ở bãi biển.", "The hotel has a private beach.", "Khách sạn có bãi biển riêng.", "Life is a beach.", "Cuộc sống như một bãi biển.", "beachy (adj)", "coast, shore", "inland"],
    ["Hotel", "Noun", "/hoʊˈtɛl/", "A1-A2", "Daily", "A place where you pay to stay when you are on holiday.", "Khách sạn", "Vào hotel để 'hô to' mà không ai nghe thấy.", ["book a hotel: đặt khách sạn", "stay in a hotel: ở khách sạn"], "We stayed at a nice hotel.", "Chúng tôi đã ở một khách sạn đẹp.", "The hotel offers free breakfast.", "Khách sạn cung cấp bữa sáng miễn phí.", "Welcome to the Hotel California.", "Chào mừng đến khách sạn California.", "motel (n)", "inn, motel", "home"],
    ["Ticket", "Noun", "/ˈtɪkɪt/", "A1-A2", "Daily", "A small piece of paper that shows you have paid to do something.", "Vé", "Ticket nghe như 'tích cắc', mua vé phải nhanh như tích cắc.", ["book a ticket: đặt vé", "plane ticket: vé máy bay"], "I bought a train ticket.", "Tôi đã mua vé tàu.", "Please show your ticket to the staff.", "Vui lòng xuất trình vé cho nhân viên.", "I got the golden ticket!", "Tôi có vé vàng rồi!", "ticketing (n)", "pass, voucher", "none"],
    ["Airport", "Noun", "/ˈɛrpɔrt/", "A1-A2", "Daily", "A place where airplanes take off and land.", "Sân bay", "Air (không khí) + port (cảng) = cảng hàng không.", ["go to the airport: đến sân bay", "international airport: sân bay quốc tế"], "We arrived at the airport early.", "Chúng tôi đến sân bay sớm.", "The airport is expanding its terminals.", "Sân bay đang mở rộng nhà ga.", "To the airport, please.", "Cho tôi đến sân bay.", "airfield (n)", "airfield, terminal", "none"],
    ["Luggage", "Noun", "/ˈlʌɡɪdʒ/", "A1-A2", "Daily", "The bags and suitcases that you carry when you travel.", "Hành lý", "Luggage nặng quá, 'lúc' nào cũng 'gãy' cả lưng.", ["carry luggage: mang hành lý", "lost luggage: hành lý thất lạc"], "Where is my luggage?", "Hành lý của tôi đâu?", "Ensure your luggage does not exceed the weight limit.", "Đảm bảo hành lý của bạn không vượt quá giới hạn cân nặng.", "Don't forget your luggage.", "Đừng quên hành lý của bạn.", "lug (v)", "baggage, gear", "none"],
    ["Trip", "Noun", "/trɪp/", "A1-A2", "Daily", "A journey in which you go somewhere and come back.", "Chuyến đi", "Trip nghe như 'chíp', đi du lịch phải chụp ảnh bằng máy chip.", ["go on a trip: đi du lịch", "business trip: chuyến công tác"], "We took a trip to the mountains.", "Chúng tôi có chuyến đi lên núi.", "He is on a business trip.", "Anh ấy đang đi công tác.", "Have a nice trip!", "Chúc chuyến đi vui vẻ!", "tripper (n)", "journey, tour", "stay"],
    ["Guide", "Noun", "/ɡaɪd/", "A1-A2", "Daily", "A person whose job is showing a place to visitors.", "Hướng dẫn viên", "Guide nghe như 'gái', cô gái hướng dẫn du lịch.", ["tour guide: hướng dẫn viên du lịch", "travel guide: sách/người hướng dẫn du lịch"], "Our guide was very friendly.", "Hướng dẫn viên của chúng tôi rất thân thiện.", "The guide explained the history of the museum.", "Hướng dẫn viên giải thích lịch sử bảo tàng.", "I need a guide.", "Tôi cần một người hướng dẫn.", "guidance (n)", "leader, director", "follower"],
    ["Passport", "Noun", "/ˈpæspɔrt/", "A1-A2", "Daily", "An official document containing personal information, needed for travel.", "Hộ chiếu", "Pass (qua) + port (cảng) = giấy tờ để qua cảng.", ["valid passport: hộ chiếu hợp lệ", "show passport: xuất trình hộ chiếu"], "Don't forget your passport.", "Đừng quên hộ chiếu của bạn.", "You must renew your passport before traveling.", "Bạn phải gia hạn hộ chiếu trước khi đi.", "Hand over your passport.", "Giao hộ chiếu của bạn ra đây.", "none", "ID, document", "none"],
    ["Tour", "Noun", "/tʊr/", "A1-A2", "Daily", "A visit to a place or area, especially one during which you look around the place.", "Chuyến du lịch/tham quan", "Tour vòng quanh thế giới.", ["guided tour: chuyến tham quan có hướng dẫn", "go on a tour: đi tham quan"], "We went on a guided tour of the city.", "Chúng tôi đi một vòng tham quan thành phố có hướng dẫn.", "The band is on tour.", "Ban nhạc đang đi lưu diễn.", "Welcome to the tour.", "Chào mừng đến với chuyến tham quan.", "tourism (n), tourist (n)", "trip, excursion", "none"],
    ["Camera", "Noun", "/ˈkæmrə/", "A1-A2", "Daily", "A device for taking photographs.", "Máy ảnh", "Cầm-ra để chụp ảnh.", ["digital camera: máy ảnh kỹ thuật số", "take a camera: mang theo máy ảnh"], "I bought a new camera for the trip.", "Tôi mua một chiếc máy ảnh mới cho chuyến đi.", "Security cameras are everywhere.", "Máy ảnh an ninh ở khắp nơi.", "Smile for the camera!", "Cười lên để chụp ảnh nào!", "cameraman (n)", "lens", "none"],
    ["Map", "Noun", "/mæp/", "A1-A2", "Daily", "A drawing of the earth's surface or part of that surface.", "Bản đồ", "Map giống như mép, dò đường từ mép này sang mép kia.", ["look at a map: nhìn bản đồ", "read a map: xem bản đồ"], "I need a map of the city.", "Tôi cần bản đồ thành phố.", "Google Maps is a digital map.", "Google Maps là một bản đồ kỹ thuật số.", "Put it on the map.", "Đưa nó lên bản đồ.", "mapping (n)", "chart, plan", "none"],
    ["Flight", "Noun", "/flaɪt/", "A1-A2", "Daily", "A journey in an aircraft.", "Chuyến bay", "Flight (bay) trên không.", ["book a flight: đặt chuyến bay", "miss a flight: lỡ chuyến bay"], "My flight is delayed.", "Chuyến bay của tôi bị hoãn.", "The flight to Paris takes 8 hours.", "Chuyến bay tới Paris mất 8 giờ.", "Boarding for flight 101.", "Mời lên máy bay cho chuyến bay 101.", "fly (v)", "journey, trip", "none"],
    ["Resort", "Noun", "/rɪˈzɔrt/", "A1-A2", "Daily", "A place where many people go for rest, sport, or another stated purpose.", "Khu nghỉ dưỡng", "Ri-xọt: nơi có nhiều thứ để ăn chơi nhảy múa.", ["beach resort: khu nghỉ dưỡng bãi biển", "luxury resort: khu nghỉ dưỡng sang trọng"], "We stayed at a luxury resort.", "Chúng tôi ở tại một khu nghỉ dưỡng sang trọng.", "The resort has a spa and tennis courts.", "Khu nghỉ dưỡng có spa và sân tennis.", "Welcome to our resort.", "Chào mừng đến khu nghỉ dưỡng của chúng tôi.", "none", "hotel, retreat", "none"],
    ["Souvenir", "Noun", "/ˌsuːvəˈnɪr/", "A1-A2", "Daily", "Something you buy to remember a holiday or special event.", "Quà lưu niệm", "Souvenir đọc nghe giống 'xu về' - mang tiền xu về làm quà.", ["buy a souvenir: mua quà lưu niệm", "souvenir shop: cửa hàng quà lưu niệm"], "I bought this mug as a souvenir.", "Tôi mua cái cốc này làm quà lưu niệm.", "Souvenir sales account for 20% of revenue.", "Doanh thu bán đồ lưu niệm chiếm 20%.", "Just a little souvenir.", "Chỉ là một chút quà lưu niệm.", "none", "memento, keepsake", "none"],
    ["Tourist", "Noun", "/ˈtʊrɪst/", "A1-A2", "Daily", "Someone who travels and visits places for fun.", "Du khách", "Tour (du lịch) + ist (người).", ["tourist attraction: điểm thu hút du khách", "tourist guide: hướng dẫn viên du lịch"], "The city is full of tourists.", "Thành phố đầy du khách.", "The local economy relies heavily on tourists.", "Nền kinh tế địa phương phụ thuộc nhiều vào du khách.", "Damn tourists!", "Lũ du khách chết tiệt!", "tourism (n)", "traveler, visitor", "local"],
    
    # B1-B2 (20)
    ["Accommodation", "Noun", "/əˌkɑməˈdeɪʃən/", "B1-B2", "Formal", "A room, group of rooms, or building in which someone may live or stay.", "Chỗ ở", "A (một) cỗ (co) xe (m) to (mo) để ở.", ["find accommodation: tìm chỗ ở", "book accommodation: đặt chỗ ở"], "We need to find accommodation for tonight.", "Chúng tôi cần tìm chỗ ở cho đêm nay.", "The price includes flights and accommodation.", "Giá bao gồm chuyến bay và chỗ ở.", "I arranged the accommodation.", "Tôi đã sắp xếp chỗ ở.", "accommodate (v)", "lodging, housing", "none"],
    ["Destination", "Noun", "/ˌdɛstɪˈneɪʃən/", "B1-B2", "Daily", "The place to which someone or something is going.", "Điểm đến", "Destin(y) - định mệnh là điểm đến.", ["popular destination: điểm đến phổ biến", "holiday destination: điểm đến kỳ nghỉ"], "Paris is a popular tourist destination.", "Paris là điểm đến du lịch phổ biến.", "We reached our destination after 10 hours.", "Chúng tôi đến nơi sau 10 giờ.", "Final destination.", "Điểm đến cuối cùng.", "destine (v)", "terminus, stop", "start"],
    ["Itinerary", "Noun", "/aɪˈtɪnərɛri/", "B1-B2", "Formal", "A detailed plan or route of a journey.", "Lịch trình", "I tin (tôi tin) rary (rất rõ) về lịch trình.", ["travel itinerary: lịch trình du lịch", "plan an itinerary: lên lịch trình"], "We have a packed itinerary for the trip.", "Chúng tôi có một lịch trình dày đặc cho chuyến đi.", "The itinerary includes a visit to the museum.", "Lịch trình bao gồm một chuyến thăm bảo tàng.", "Stick to the itinerary.", "Bám sát lịch trình.", "itinerant (adj)", "schedule, plan", "none"],
    ["Sightseeing", "Noun", "/ˈsaɪtˌsiːɪŋ/", "B1-B2", "Daily", "The activity of visiting interesting places, especially by people on holiday.", "Ngắm cảnh", "Sight (cảnh) + seeing (nhìn).", ["go sightseeing: đi ngắm cảnh", "sightseeing tour: chuyến đi ngắm cảnh"], "We did a lot of sightseeing in Rome.", "Chúng tôi đã đi ngắm cảnh rất nhiều ở Rome.", "Sightseeing is a major part of the tourism industry.", "Ngắm cảnh là một phần lớn của ngành du lịch.", "Let's go sightseeing.", "Đi ngắm cảnh thôi.", "sightseer (n)", "touring, visiting", "none"],
    ["Excursion", "Noun", "/ɪkˈskɜrʒən/", "B1-B2", "Formal", "A short journey or trip, especially one engaged in as a leisure activity.", "Chuyến dã ngoại/du ngoạn", "Ex (ra ngoài) + cursion.", ["day excursion: chuyến du ngoạn trong ngày", "go on an excursion: đi dã ngoại"], "We went on a brief excursion to the coast.", "Chúng tôi đi dã ngoại ngắn ra bờ biển.", "The company organized an excursion for employees.", "Công ty tổ chức chuyến dã ngoại cho nhân viên.", "It's just a little excursion.", "Đó chỉ là một chuyến du ngoạn nhỏ.", "none", "trip, outing", "none"],
    ["Reservation", "Noun", "/ˌrɛzərˈveɪʃən/", "B1-B2", "Daily", "An arrangement in which something such as a seat on an aircraft or a table at a restaurant is kept for you.", "Sự đặt chỗ", "Reserve (đặt trước) + ation.", ["make a reservation: đặt chỗ", "confirm a reservation: xác nhận đặt chỗ"], "I made a reservation at the restaurant.", "Tôi đã đặt chỗ ở nhà hàng.", "Your reservation is confirmed.", "Việc đặt chỗ của bạn đã được xác nhận.", "I have a reservation under Smith.", "Tôi có đặt chỗ dưới tên Smith.", "reserve (v)", "booking", "none"],
    ["Departure", "Noun", "/dɪˈpɑrtʃər/", "B1-B2", "Formal", "The action of leaving, typically to start a journey.", "Sự khởi hành", "Depart (khởi hành) + ure.", ["departure time: giờ khởi hành", "departure lounge: phòng chờ khởi hành"], "The departure was delayed by an hour.", "Sự khởi hành bị trễ một giờ.", "Please proceed to the departure gate.", "Vui lòng tiến tới cổng khởi hành.", "Immediate departure.", "Khởi hành ngay lập tức.", "depart (v)", "leaving, exit", "arrival"],
    ["Arrival", "Noun", "/əˈraɪvəl/", "B1-B2", "Formal", "The act of arriving somewhere.", "Sự đến nơi", "Arrive (đến) + al.", ["arrival time: giờ đến", "new arrival: người mới đến"], "We waited for his arrival.", "Chúng tôi chờ sự đến nơi của anh ấy.", "The expected time of arrival is 8 PM.", "Thời gian dự kiến đến là 8 giờ tối.", "Arrivals are on the first floor.", "Khu vực đến nằm ở tầng một.", "arrive (v)", "coming, appearance", "departure"],
    ["Backpacking", "Noun", "/ˈbækˌpækɪŋ/", "B1-B2", "Daily", "Travelling or camping with your clothes and belongings in a backpack.", "Du lịch ba lô", "Backpack (ba lô) + ing.", ["go backpacking: đi du lịch ba lô", "backpacking trip: chuyến du lịch ba lô"], "He went backpacking across Europe.", "Anh ấy đã đi du lịch ba lô xuyên châu Âu.", "Backpacking is popular among young adults.", "Du lịch ba lô phổ biến ở giới trẻ.", "Backpacking is fun.", "Du lịch ba lô rất vui.", "backpack (n)", "trekking", "none"],
    ["Journey", "Noun", "/ˈdʒɜrni/", "B1-B2", "Formal", "The act of travelling from one place to another, especially in a vehicle.", "Hành trình", "Jour (ngày) + ney, hành trình kéo dài nhiều ngày.", ["long journey: hành trình dài", "safe journey: hành trình an toàn"], "It was a long journey by train.", "Đó là một hành trình dài bằng tàu.", "The journey of a thousand miles begins with a single step.", "Hành trình vạn dặm bắt đầu từ một bước chân.", "Enjoy your journey.", "Tận hưởng hành trình của bạn nhé.", "none", "trip, voyage", "none"],
    ["Voyage", "Noun", "/ˈvɔɪɪdʒ/", "B1-B2", "Formal", "A long journey involving travel by sea or in space.", "Chuyến đi xa (biển/không gian)", "Voy (vòi) ra biển lớn.", ["maiden voyage: chuyến đi đầu tiên", "sea voyage: chuyến đi biển"], "The Titanic sank on its maiden voyage.", "Tàu Titanic chìm trong chuyến đi đầu tiên.", "Space is a voyage of discovery.", "Không gian là một chuyến đi khám phá.", "Bon voyage!", "Thượng lộ bình an!", "voyager (n)", "journey, cruise", "none"],
    ["Cruise", "Noun", "/kruz/", "B1-B2", "Daily", "A journey on a large ship for pleasure.", "Du thuyền/Chuyến du ngoạn trên biển", "Cruise nghe như 'cờ-ru', đi du thuyền với crush.", ["go on a cruise: đi du thuyền", "cruise ship: tàu du lịch"], "They went on a Caribbean cruise.", "Họ đi du ngoạn vùng Caribbean trên tàu.", "The cruise industry is recovering.", "Ngành du thuyền đang hồi phục.", "We are on a cruise.", "Chúng tôi đang ở trên một du thuyền.", "cruiser (n)", "voyage, sail", "none"],
    ["Expedition", "Noun", "/ˌɛkspɪˈdɪʃən/", "B1-B2", "Formal", "A journey or voyage undertaken by a group of people with a particular purpose.", "Cuộc thám hiểm", "Ex (ra) + ped (chân), mang chân đi khám phá.", ["scientific expedition: cuộc thám hiểm khoa học", "go on an expedition: đi thám hiểm"], "They went on an expedition to the Amazon.", "Họ đi thám hiểm vùng Amazon.", "The expedition was well-funded.", "Cuộc thám hiểm được tài trợ tốt.", "The expedition starts tomorrow.", "Cuộc thám hiểm bắt đầu vào ngày mai.", "expedite (v)", "journey, exploration", "none"],
    ["Landmark", "Noun", "/ˈlændˌmɑrk/", "B1-B2", "Daily", "An object or feature of a landscape or town that is easily seen and recognized from a distance.", "Điểm mốc/Danh thắng", "Land (đất) + mark (đánh dấu).", ["famous landmark: danh thắng nổi tiếng", "historic landmark: di tích lịch sử"], "The Eiffel Tower is a famous landmark.", "Tháp Eiffel là một danh thắng nổi tiếng.", "The decision is a landmark in legal history.", "Quyết định là một cột mốc trong lịch sử pháp lý.", "Look at that landmark.", "Nhìn cột mốc kia kìa.", "none", "monument", "none"],
    ["Stopover", "Noun", "/ˈstɑpˌoʊvər/", "B1-B2", "Daily", "A short stay in a place that you make while you are on a longer journey.", "Điểm dừng chân", "Stop (dừng) + over (qua).", ["have a stopover: có một điểm dừng", "a brief stopover: điểm dừng ngắn"], "We had a stopover in Dubai.", "Chúng tôi có một điểm dừng chân ở Dubai.", "The stopover allowed for refueling.", "Điểm dừng cho phép nạp nhiên liệu.", "It's just a stopover.", "Đó chỉ là một điểm dừng chân.", "none", "layover", "none"],
    ["Getaway", "Noun", "/ˈɡɛtəˌweɪ/", "B1-B2", "Daily", "A short holiday or place where you can make a holiday.", "Kỳ nghỉ ngắn/Nơi trốn tìm", "Get (lấy) + away (đi xa), đi trốn.", ["weekend getaway: kỳ nghỉ cuối tuần", "romantic getaway: kỳ nghỉ lãng mạn"], "We planned a weekend getaway.", "Chúng tôi lên kế hoạch một kỳ nghỉ cuối tuần.", "The cabin is a perfect getaway.", "Căn chòi là một nơi nghỉ ngơi hoàn hảo.", "Make a clean getaway.", "Tẩu thoát trót lọt.", "get away (v)", "escape, retreat", "none"],
    ["Boarding", "Noun", "/ˈbɔrdɪŋ/", "B1-B2", "Daily", "The act of passengers and crew getting aboard a ship or aircraft.", "Sự lên tàu/máy bay", "Board (bảng/lên tàu) + ing.", ["boarding pass: thẻ lên máy bay", "boarding time: giờ lên máy bay"], "Show your boarding pass.", "Xuất trình thẻ lên máy bay của bạn.", "Boarding commences in 10 minutes.", "Việc lên máy bay bắt đầu trong 10 phút.", "Boarding is complete.", "Quá trình lên máy bay hoàn tất.", "board (v)", "embarkation", "disembarkation"],
    ["Passenger", "Noun", "/ˈpæsəndʒər/", "B1-B2", "Daily", "A person who is traveling in a vehicle but is not driving it.", "Hành khách", "Pass (qua) + enger (người), người đi ngang qua.", ["train passenger: hành khách đi tàu", "passenger seat: ghế hành khách"], "The car can hold four passengers.", "Xe ô tô có thể chở bốn hành khách.", "Passenger safety is our top priority.", "An toàn của hành khách là ưu tiên hàng đầu.", "Attention, all passengers.", "Chú ý, tất cả hành khách.", "none", "traveler, rider", "driver"],
    ["Scenery", "Noun", "/ˈsinəri/", "B1-B2", "Daily", "The general appearance of the natural environment, especially when it is beautiful.", "Phong cảnh", "Scene (cảnh) + ry.", ["beautiful scenery: phong cảnh đẹp", "enjoy the scenery: thưởng thức phong cảnh"], "The scenery in the mountains is beautiful.", "Phong cảnh ở núi rất đẹp.", "We stopped to admire the scenery.", "Chúng tôi dừng lại để chiêm ngưỡng phong cảnh.", "Look at this scenery!", "Nhìn phong cảnh này xem!", "scenic (adj)", "landscape, view", "none"],
    ["Leisure", "Noun", "/ˈliʒər/", "B1-B2", "Formal", "Time when one is not working or occupied; free time.", "Thời gian rảnh/Giải trí", "Lei (lấy) + sure (chắc chắn), lúc rảnh thì chắc chắn lấy ra chơi.", ["leisure time: thời gian rảnh rỗi", "leisure activities: hoạt động giải trí"], "I read books at my leisure.", "Tôi đọc sách vào thời gian rảnh.", "The leisure industry is growing.", "Ngành công nghiệp giải trí đang phát triển.", "Gentlemen of leisure.", "Những quý ông rảnh rỗi.", "leisurely (adj)", "free time, relaxation", "work"],
    
    # C1-C2 (15)
    ["Escapade", "Noun", "/ˈɛskəˌpeɪd/", "C1-C2", "Formal", "An act or incident involving excitement, daring, or adventure.", "Cuộc phiêu lưu", "Escape (trốn thoát) + ade, đi trốn để phiêu lưu.", ["reckless escapade: cuộc phiêu lưu liều lĩnh", "weekend escapade: cuộc phiêu lưu cuối tuần"], "Their weekend escapade ended in disaster.", "Cuộc phiêu lưu cuối tuần của họ kết thúc trong thảm họa.", "He is known for his romantic escapades.", "Anh ta nổi tiếng với những cuộc phiêu lưu tình ái.", "A little escapade never hurt anyone.", "Một chuyến phiêu lưu nhỏ không hại ai cả.", "none", "adventure, exploit", "routine"],
    ["Sojourn", "Noun", "/ˈsoʊdʒɜrn/", "C1-C2", "Academic", "A temporary stay.", "Sự lưu trú tạm thời", "So (rất) + journ (hành trình), hành trình phải có lúc dừng chân.", ["brief sojourn: lần lưu lại ngắn", "summer sojourn: kỳ nghỉ hè"], "My sojourn in Paris was delightful.", "Kỳ lưu trú của tôi ở Paris rất thú vị.", "During his sojourn in Africa, he learned a lot.", "Trong thời gian lưu trú ở châu Phi, anh học được nhiều điều.", "A brief sojourn in hell.", "Một cuộc dạo chơi ngắn dưới địa ngục.", "sojourner (n)", "stay, visit", "departure"],
    ["Odyssey", "Noun", "/ˈɑdəsi/", "C1-C2", "Academic", "A long and eventful or adventurous journey or experience.", "Hành trình dài và gian nan", "Bắt nguồn từ trường ca Odyssey của Homer.", ["spiritual odyssey: hành trình tâm linh", "epic odyssey: hành trình sử thi"], "His life was a remarkable odyssey.", "Cuộc đời anh là một hành trình dài đáng nhớ.", "The project turned into a ten-year odyssey.", "Dự án biến thành một hành trình 10 năm gian nan.", "A space odyssey.", "Một chuyến du hành không gian.", "none", "journey, voyage", "none"],
    ["Globetrotting", "Noun", "/ˈɡloʊbˌtrɑtɪŋ/", "C1-C2", "Formal", "The action of traveling widely around the world.", "Du lịch vòng quanh thế giới", "Globe (địa cầu) + trotting (chạy chậm).", ["frequent globetrotting: thường xuyên du lịch thế giới", "years of globetrotting: những năm tháng đi vòng quanh thế giới"], "Her job involves a lot of globetrotting.", "Công việc của cô ấy liên quan đến việc du lịch thế giới rất nhiều.", "Globetrotting executives face unique challenges.", "Các giám đốc đi lại nhiều đối mặt với thách thức riêng.", "I'm done with globetrotting.", "Tôi chán đi vòng quanh thế giới rồi.", "globetrotter (n)", "traveling", "staying"],
    ["Wayfarer", "Noun", "/ˈweɪˌfɛrər/", "C1-C2", "Formal", "A person who travels on foot.", "Khách bộ hành", "Way (đường) + fare (đi).", ["weary wayfarer: khách bộ hành mệt mỏi", "lone wayfarer: khách bộ hành đơn độc"], "The inn provided shelter for weary wayfarers.", "Quán trọ cung cấp chỗ nghỉ cho những khách bộ hành mệt mỏi.", "Historically, wayfarers relied on hospitality.", "Trong lịch sử, khách bộ hành phụ thuộc vào lòng hiếu khách.", "Greetings, wayfarer.", "Chào khách bộ hành.", "wayfaring (adj)", "traveler, wanderer", "resident"],
    ["Peregrination", "Noun", "/ˌpɛrɪɡrɪˈneɪʃən/", "C1-C2", "Academic", "A journey, especially a long or meandering one.", "Cuộc du hành", "Pere (qua) + agri (đồng), đi qua nhiều vùng.", ["endless peregrinations: những chuyến đi bất tận", "intellectual peregrination: hành trình tri thức"], "His peregrinations took him to Asia.", "Các chuyến du hành đã đưa ông tới châu Á.", "The book describes her peregrinations.", "Cuốn sách mô tả các cuộc du hành của cô.", "Enough of these peregrinations.", "Đủ cho những chuyến đi này rồi.", "peregrinate (v)", "travels, wandering", "settlement"],
    ["Ecotourism", "Noun", "/ˈikoʊˌtʊrɪzəm/", "C1-C2", "Academic", "Tourism directed toward exotic, often threatened, natural environments, intended to support conservation efforts.", "Du lịch sinh thái", "Eco (sinh thái) + tourism (du lịch).", ["promote ecotourism: thúc đẩy du lịch sinh thái", "sustainable ecotourism: du lịch sinh thái bền vững"], "Costa Rica is famous for its ecotourism.", "Costa Rica nổi tiếng với du lịch sinh thái.", "Ecotourism minimizes environmental impact.", "Du lịch sinh thái giảm thiểu tác động môi trường.", "Ecotourism is the future.", "Du lịch sinh thái là tương lai.", "ecotourist (n)", "sustainable tourism", "mass tourism"],
    ["Unwind", "Verb", "/ʌnˈwaɪnd/", "C1-C2", "Daily", "To relax after a period of work or tension.", "Thư giãn", "Un (ngược lại) + wind (cuộn), tháo gỡ sự căng thẳng.", ["unwind completely: thư giãn hoàn toàn", "time to unwind: thời gian để thư giãn"], "I need a drink to unwind.", "Tôi cần một ly đồ uống để thư giãn.", "Listening to music helps patients unwind.", "Nghe nhạc giúp bệnh nhân thư giãn.", "Let's just sit back and unwind.", "Hãy ngồi xuống và thư giãn.", "none", "relax, chill", "stress"],
    ["Respite", "Noun", "/ˈrɛspɪt/", "C1-C2", "Formal", "A short period of rest or relief from something difficult or unpleasant.", "Sự nghỉ ngơi/Thời gian ân xá", "Re (lại) + spite (nhìn), nhìn lại để nghỉ ngơi.", ["brief respite: thời gian nghỉ ngơi ngắn", "respite care: chăm sóc thay thế tạm thời"], "The weekend provided a brief respite from work.", "Cuối tuần mang lại một thời gian nghỉ ngơi ngắn khỏi công việc.", "The drug brought a temporary respite from the pain.", "Thuốc mang lại một sự giảm đau tạm thời.", "We have no respite.", "Chúng ta không có thời gian nghỉ.", "none", "break, relief", "continuation"],
    ["Tranquility", "Noun", "/træŋˈkwɪlɪti/", "C1-C2", "Formal", "The quality or state of being tranquil; calm.", "Sự yên bình", "Tranquil (yên tĩnh) + ity.", ["peace and tranquility: hòa bình và yên tĩnh", "absolute tranquility: sự yên bình tuyệt đối"], "I love the tranquility of the countryside.", "Tôi yêu sự yên bình của vùng nông thôn.", "The resort offers a sense of tranquility.", "Khu nghỉ dưỡng mang lại cảm giác yên bình.", "Find your inner tranquility.", "Tìm kiếm sự yên bình nội tại.", "tranquil (adj)", "peace, calm", "chaos"],
    ["Reprieve", "Noun", "/rɪˈpriv/", "C1-C2", "Formal", "A cancellation or postponement of a punishment; a temporary escape.", "Sự ân giảm/Sự hoãn lại", "Re (lại) + prieve (bắt), bắt lại sau.", ["temporary reprieve: sự hoãn lại tạm thời", "grant a reprieve: ban cho sự ân giảm"], "The rain provided a reprieve from the heat.", "Cơn mưa mang lại một sự hoãn lại khỏi cái nóng.", "He was saved from the gallows by a last-minute reprieve.", "Anh ta được cứu khỏi giá treo cổ nhờ sự ân giảm phút chót.", "You got a reprieve.", "Ngươi vừa được hoãn án phạt.", "reprieve (v)", "pardon, delay", "punishment"],
    ["Disembark", "Verb", "/ˌdɪsɪmˈbɑrk/", "C1-C2", "Formal", "To leave a ship, aircraft, or other vehicle.", "Xuống tàu/máy bay", "Dis (khỏi) + embark (lên tàu).", ["disembark from: xuống từ", "ready to disembark: sẵn sàng xuống tàu"], "Passengers will disembark shortly.", "Hành khách sẽ xuống tàu sớm.", "Disembarking passengers should proceed to customs.", "Hành khách xuống máy bay nên đi tới hải quan.", "Time to disembark.", "Đã đến lúc xuống tàu.", "disembarkation (n)", "leave, alight", "embark"],
    ["Wanderlust", "Noun", "/ˈwɑndərˌlʌst/", "C1-C2", "Daily", "A strong desire to travel.", "Niềm đam mê du lịch", "Wander (lang thang) + lust (thèm khát).", ["have wanderlust: có đam mê du lịch", "suffer from wanderlust: bị hội chứng cuồng chân"], "His wanderlust led him all over the world.", "Niềm đam mê du lịch dẫn anh đi khắp thế giới.", "Wanderlust is common among millennials.", "Đam mê du lịch rất phổ biến trong thế hệ Y.", "Got a bad case of wanderlust.", "Đang cuồng chân quá.", "none", "travel bug", "homebody"],
    ["Picturesque", "Adjective", "/ˌpɪktʃəˈrɛsk/", "C1-C2", "Formal", "Visually attractive, especially in a quaint or pretty style.", "Đẹp như tranh vẽ", "Picture (tranh) + esque (như).", ["picturesque village: ngôi làng đẹp như tranh", "picturesque scenery: phong cảnh đẹp như tranh"], "We visited a picturesque village in the Alps.", "Chúng tôi thăm một ngôi làng đẹp như tranh ở dãy Alps.", "The novel is set in a picturesque coastal town.", "Cuốn tiểu thuyết lấy bối cảnh ở một thị trấn ven biển đẹp như tranh.", "What a picturesque view.", "Quả là một khung cảnh đẹp như tranh.", "none", "scenic, beautiful", "ugly"],
    ["Breathtaking", "Adjective", "/ˈbrɛθˌteɪkɪŋ/", "C1-C2", "Daily", "Astonishing or awe-inspiring in quality, so as to take one's breath away.", "Ngoạn mục", "Breath (hơi thở) + taking (lấy đi), đẹp đến nghẹt thở.", ["breathtaking view: cảnh đẹp ngoạn mục", "breathtaking performance: màn trình diễn ngoạn mục"], "The view from the top is breathtaking.", "Cảnh từ trên đỉnh thật ngoạn mục.", "The speed of technological change is breathtaking.", "Tốc độ thay đổi công nghệ thật đáng kinh ngạc.", "That was breathtaking.", "Điều đó thật ngoạn mục.", "breathtakingly (adv)", "stunning, magnificent", "unimpressive"]
]

template = """# {word}
*{pos}*
> {ipa}

---
**Level:** {lvl} | **Ngữ cảnh:** {ctx} | **Chủ đề:** {topic}

## 📌 Ý nghĩa (Meaning)
- **[EN]:** {en}
- **[VN]:** {vn}

## 🧠 Mẹo nhớ (Mnemonics)
💡 {m}

## 🧩 Cụm từ thường đi kèm (Collocations)
{cols}

## 🎬 Ví dụ thực tế (Real-world Examples)
1. 💬 *Daily:* {ex1}
   *-> {ex1v}*
2. 💼 *Work/Academic:* {ex2}
   *-> {ex2v}*
3. 🎬 *Media/Movie:* {ex3}
   *-> {ex3v}*

## 🕸️ Mạng lưới từ (Word Network)
**Word Family:**
- {fam}

**Synonyms:** {syn}
**Antonyms:** {ant}
"""

for w in words:
    word, pos, ipa, lvl, ctx, en, vn, m, cols_list, ex1, ex1v, ex2, ex2v, ex3, ex3v, fam, syn, ant = w
    cols_str = "\n".join([f"- `{c.split(': ')[0]}`: {c.split(': ')[1]}" for c in cols_list])
    
    content = template.format(
        word=word, pos=pos, ipa=ipa, lvl=lvl, ctx=ctx, topic=topic,
        en=en, vn=vn, m=m, cols=cols_str,
        ex1=ex1, ex1v=ex1v, ex2=ex2, ex2v=ex2v, ex3=ex3, ex3v=ex3v,
        fam=fam, syn=syn, ant=ant
    )
    
    file_path = os.path.join(target_dir, f"{word}.md")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

print(f"Generated {len(words)} vocabulary files in {target_dir}")
