import os
import json

data = [
    # A1-A2
    {"w": "Good", "pos": "adj.", "ipa": "/ɡʊd/", "lvl": "A1", "ctx": "Daily", "en": "Of high quality", "vn": "Tốt", "m": "Good là tốt", "col": "`good day`: ngày tốt", "ex1": "Have a good day.", "ex1v": "Chúc một ngày tốt lành.", "ex2": "She did a good job.", "ex2v": "Cô ấy làm tốt.", "ex3": "A good movie.", "ex3v": "Phim hay.", "fam": "goodness", "syn": "great", "ant": "bad"},
    {"w": "Bad", "pos": "adj.", "ipa": "/bæd/", "lvl": "A1", "ctx": "Daily", "en": "Of poor quality", "vn": "Xấu, tệ", "m": "Bad là tệ", "col": "`bad weather`: thời tiết xấu", "ex1": "It is bad.", "ex1v": "Nó tệ.", "ex2": "Bad performance.", "ex2v": "Hiệu suất kém.", "ex3": "Breaking Bad.", "ex3v": "Tập làm người xấu.", "fam": "badly", "syn": "poor", "ant": "good"},
    {"w": "Big", "pos": "adj.", "ipa": "/bɪɡ/", "lvl": "A1", "ctx": "Daily", "en": "Of large size", "vn": "Lớn", "m": "Big là to lớn", "col": "`big deal`: chuyện lớn", "ex1": "A big house.", "ex1v": "Ngôi nhà lớn.", "ex2": "Big project.", "ex2v": "Dự án lớn.", "ex3": "Mr. Big.", "ex3v": "Ông lớn.", "fam": "bigness", "syn": "large", "ant": "small"},
    {"w": "Small", "pos": "adj.", "ipa": "/smɔːl/", "lvl": "A1", "ctx": "Daily", "en": "Of a size that is less than normal", "vn": "Nhỏ", "m": "Small là nhỏ", "col": "`small talk`: chuyện phiếm", "ex1": "Small dog.", "ex1v": "Chó nhỏ.", "ex2": "Small business.", "ex2v": "Doanh nghiệp nhỏ.", "ex3": "Small Soldiers.", "ex3v": "Lính nhỏ.", "fam": "smallness", "syn": "tiny", "ant": "big"},
    {"w": "Hot", "pos": "adj.", "ipa": "/hɒt/", "lvl": "A1", "ctx": "Daily", "en": "Having a high degree of heat", "vn": "Nóng", "m": "Hot là nóng", "col": "`hot water`: nước nóng", "ex1": "It is hot.", "ex1v": "Trời nóng.", "ex2": "Hot topic.", "ex2v": "Chủ đề nóng.", "ex3": "Hot Fuzz.", "ex3v": "Siêu cớm.", "fam": "hotly", "syn": "warm", "ant": "cold"},
    {"w": "Cold", "pos": "adj.", "ipa": "/kəʊld/", "lvl": "A1", "ctx": "Daily", "en": "Of or at a low temperature", "vn": "Lạnh", "m": "Cold là lạnh", "col": "`cold weather`: thời tiết lạnh", "ex1": "I am cold.", "ex1v": "Tôi lạnh.", "ex2": "Cold call.", "ex2v": "Gọi điện chào hàng.", "ex3": "Cold Mountain.", "ex3v": "Núi lạnh.", "fam": "coldness", "syn": "chilly", "ant": "hot"},
    {"w": "Happy", "pos": "adj.", "ipa": "/ˈhæpi/", "lvl": "A1", "ctx": "Daily", "en": "Feeling or showing pleasure", "vn": "Hạnh phúc, vui", "m": "Happy là vui vẻ", "col": "`happy ending`: kết thúc có hậu", "ex1": "I am happy.", "ex1v": "Tôi vui.", "ex2": "Happy client.", "ex2v": "Khách hàng hài lòng.", "ex3": "Happy Feet.", "ex3v": "Vũ điệu chim cánh cụt.", "fam": "happiness", "syn": "glad", "ant": "sad"},
    {"w": "Sad", "pos": "adj.", "ipa": "/sæd/", "lvl": "A1", "ctx": "Daily", "en": "Feeling or showing sorrow", "vn": "Buồn", "m": "Sad là buồn", "col": "`sad news`: tin buồn", "ex1": "I feel sad.", "ex1v": "Tôi thấy buồn.", "ex2": "Sad reality.", "ex2v": "Thực tế buồn.", "ex3": "Sad song.", "ex3v": "Bài hát buồn.", "fam": "sadness", "syn": "unhappy", "ant": "happy"},
    {"w": "Fast", "pos": "adj.", "ipa": "/fɑːst/", "lvl": "A1", "ctx": "Daily", "en": "Moving or capable of moving at high speed", "vn": "Nhanh", "m": "Fast là nhanh", "col": "`fast food`: thức ăn nhanh", "ex1": "Run fast.", "ex1v": "Chạy nhanh.", "ex2": "Fast growth.", "ex2v": "Tăng trưởng nhanh.", "ex3": "Fast and Furious.", "ex3v": "Quá nhanh quá nguy hiểm.", "fam": "fastness", "syn": "quick", "ant": "slow"},
    {"w": "Slow", "pos": "adj.", "ipa": "/sləʊ/", "lvl": "A1", "ctx": "Daily", "en": "Moving or operating at a low speed", "vn": "Chậm", "m": "Slow là chậm", "col": "`slow motion`: quay chậm", "ex1": "Walk slow.", "ex1v": "Đi chậm.", "ex2": "Slow progress.", "ex2v": "Tiến độ chậm.", "ex3": "Slow horses.", "ex3v": "Những chú ngựa chậm chạp.", "fam": "slowly", "syn": "unhurried", "ant": "fast"},
    {"w": "Tall", "pos": "adj.", "ipa": "/tɔːl/", "lvl": "A1", "ctx": "Daily", "en": "Of great or more than average height", "vn": "Cao", "m": "Tall là cao", "col": "`tall building`: tòa nhà cao", "ex1": "He is tall.", "ex1v": "Anh ấy cao.", "ex2": "Tall order.", "ex2v": "Yêu cầu khó.", "ex3": "Tall Girl.", "ex3v": "Cô gái cao kều.", "fam": "tallness", "syn": "high", "ant": "short"},
    {"w": "Short", "pos": "adj.", "ipa": "/ʃɔːt/", "lvl": "A1", "ctx": "Daily", "en": "Measuring a small distance from end to end", "vn": "Ngắn, thấp", "m": "Short là ngắn", "col": "`short time`: thời gian ngắn", "ex1": "Short hair.", "ex1v": "Tóc ngắn.", "ex2": "Short notice.", "ex2v": "Thông báo gấp.", "ex3": "The Big Short.", "ex3v": "Đại suy thoái.", "fam": "shortness", "syn": "brief", "ant": "long"},
    {"w": "Easy", "pos": "adj.", "ipa": "/ˈiːzi/", "lvl": "A1", "ctx": "Daily", "en": "Achieved without great effort", "vn": "Dễ dàng", "m": "Easy là dễ", "col": "`easy way`: cách dễ", "ex1": "It is easy.", "ex1v": "Nó dễ.", "ex2": "Easy task.", "ex2v": "Nhiệm vụ dễ.", "ex3": "Easy A.", "ex3v": "Cô nàng lẳng lơ.", "fam": "easily", "syn": "simple", "ant": "hard"},
    {"w": "Hard", "pos": "adj.", "ipa": "/hɑːd/", "lvl": "A1", "ctx": "Daily", "en": "Requiring a great deal of endurance or effort", "vn": "Khó, cứng", "m": "Hard là khó", "col": "`hard work`: công việc chăm chỉ", "ex1": "It is hard.", "ex1v": "Nó khó.", "ex2": "Hard decision.", "ex2v": "Quyết định khó khăn.", "ex3": "Die Hard.", "ex3v": "Đương đầu với thử thách.", "fam": "hardness", "syn": "difficult", "ant": "easy"},
    {"w": "New", "pos": "adj.", "ipa": "/njuː/", "lvl": "A1", "ctx": "Daily", "en": "Produced, introduced, or discovered recently", "vn": "Mới", "m": "New là mới", "col": "`new year`: năm mới", "ex1": "New car.", "ex1v": "Xe mới.", "ex2": "New employee.", "ex2v": "Nhân viên mới.", "ex3": "New Girl.", "ex3v": "Cô gái mới.", "fam": "newly", "syn": "fresh", "ant": "old"},

    # B1-B2
    {"w": "Amazing", "pos": "adj.", "ipa": "/əˈmeɪzɪŋ/", "lvl": "B1", "ctx": "Daily", "en": "Causing great surprise or wonder", "vn": "Tuyệt vời", "m": "Mê mẩn vì nó amazing", "col": "`amazing experience`: trải nghiệm tuyệt vời", "ex1": "You look amazing.", "ex1v": "Bạn trông tuyệt vời.", "ex2": "Amazing results.", "ex2v": "Kết quả đáng kinh ngạc.", "ex3": "Amazing Spider-Man.", "ex3v": "Người Nhện siêu đẳng.", "fam": "amazement", "syn": "incredible", "ant": "ordinary"},
    {"w": "Awful", "pos": "adj.", "ipa": "/ˈɔːfl/", "lvl": "B1", "ctx": "Daily", "en": "Very bad or unpleasant", "vn": "Tồi tệ", "m": "Ồ, ful lầm lỗi nên awful", "col": "`awful truth`: sự thật phũ phàng", "ex1": "Awful smell.", "ex1v": "Mùi kinh khủng.", "ex2": "Awful mistake.", "ex2v": "Sai lầm tồi tệ.", "ex3": "Awful truth.", "ex3v": "Sự thật tồi tệ.", "fam": "awfully", "syn": "terrible", "ant": "wonderful"},
    {"w": "Enormous", "pos": "adj.", "ipa": "/ɪˈnɔːməs/", "lvl": "B1", "ctx": "Academic", "en": "Very large in size, quantity, or extent", "vn": "To lớn, khổng lồ", "m": "E nơ mút (nấm) to lớn", "col": "`enormous impact`: tác động to lớn", "ex1": "Enormous dog.", "ex1v": "Chó khổng lồ.", "ex2": "Enormous profit.", "ex2v": "Lợi nhuận khổng lồ.", "ex3": "Enormous crocodile.", "ex3v": "Cá sấu khổng lồ.", "fam": "enormity", "syn": "huge", "ant": "tiny"},
    {"w": "Tiny", "pos": "adj.", "ipa": "/ˈtaɪni/", "lvl": "B1", "ctx": "Daily", "en": "Very small", "vn": "Nhỏ xíu", "m": "Tí nị là tiny", "col": "`tiny detail`: chi tiết nhỏ", "ex1": "Tiny bug.", "ex1v": "Con bọ nhỏ xíu.", "ex2": "Tiny fraction.", "ex2v": "Phần nhỏ xíu.", "ex3": "Tiny Toons.", "ex3v": "Phim hoạt hình Tiny.", "fam": "tininess", "syn": "minute", "ant": "enormous"},
    {"w": "Freezing", "pos": "adj.", "ipa": "/ˈfriːzɪŋ/", "lvl": "B1", "ctx": "Daily", "en": "Below 0°C; very cold", "vn": "Lạnh cóng", "m": "Free (tủ lạnh) zing (run) -> lạnh cóng", "col": "`freezing cold`: lạnh buốt", "ex1": "I am freezing.", "ex1v": "Tôi lạnh cóng.", "ex2": "Freezing point.", "ex2v": "Điểm đóng băng.", "ex3": "Frozen.", "ex3v": "Nữ hoàng băng giá.", "fam": "freeze", "syn": "icy", "ant": "boiling"},
    {"w": "Boiling", "pos": "adj.", "ipa": "/ˈbɔɪlɪŋ/", "lvl": "B1", "ctx": "Daily", "en": "Extremely hot", "vn": "Nóng sôi", "m": "Boi (sôi) linh -> sôi sục", "col": "`boiling hot`: nóng sôi", "ex1": "It's boiling today.", "ex1v": "Hôm nay nóng sôi.", "ex2": "Boiling point.", "ex2v": "Điểm sôi.", "ex3": "Boiling Room.", "ex3v": "Phòng sôi.", "fam": "boil", "syn": "scorching", "ant": "freezing"},
    {"w": "Delighted", "pos": "adj.", "ipa": "/dɪˈlaɪtɪd/", "lvl": "B1", "ctx": "Formal", "en": "Feeling or showing great pleasure", "vn": "Vui mừng", "m": "Đi lại tít mắt vì vui mừng", "col": "`delighted to hear`: vui mừng khi nghe", "ex1": "I'm delighted.", "ex1v": "Tôi rất vui.", "ex2": "Delighted customer.", "ex2v": "Khách hàng vui mừng.", "ex3": "Delighted expression.", "ex3v": "Biểu cảm vui mừng.", "fam": "delight", "syn": "thrilled", "ant": "disappointed"},
    {"w": "Miserable", "pos": "adj.", "ipa": "/ˈmɪzrəbl/", "lvl": "B1", "ctx": "Daily", "en": "Wretchedly unhappy or uncomfortable", "vn": "Khốn khổ", "m": "Mi sợ (miserable) khổ", "col": "`miserable life`: cuộc sống khốn khổ", "ex1": "I feel miserable.", "ex1v": "Tôi thấy khốn khổ.", "ex2": "Miserable failure.", "ex2v": "Thất bại thảm hại.", "ex3": "Les Misérables.", "ex3v": "Những người khốn khổ.", "fam": "misery", "syn": "unhappy", "ant": "cheerful"},
    {"w": "Gorgeous", "pos": "adj.", "ipa": "/ˈɡɔːdʒəs/", "lvl": "B2", "ctx": "Daily", "en": "Beautiful, very attractive", "vn": "Tuyệt đẹp", "m": "Gió rét (gorgeous) vẫn thấy đẹp", "col": "`gorgeous view`: khung cảnh tuyệt đẹp", "ex1": "Gorgeous dress.", "ex1v": "Váy tuyệt đẹp.", "ex2": "Gorgeous design.", "ex2v": "Thiết kế tuyệt đẹp.", "ex3": "Gorgeous George.", "ex3v": "George tuyệt đẹp.", "fam": "gorgeously", "syn": "stunning", "ant": "ugly"},
    {"w": "Hideous", "pos": "adj.", "ipa": "/ˈhɪdiəs/", "lvl": "B2", "ctx": "Daily", "en": "Extremely ugly", "vn": "Gớm ghiếc", "m": "Hi đi (hideous) vì gớm", "col": "`hideous monster`: quái vật gớm ghiếc", "ex1": "Hideous shirt.", "ex1v": "Áo gớm ghiếc.", "ex2": "Hideous crime.", "ex2v": "Tội ác gớm ghiếc.", "ex3": "Hideous Kinky.", "ex3v": "Kỳ cục.", "fam": "hideousness", "syn": "repulsive", "ant": "beautiful"},
    {"w": "Rapid", "pos": "adj.", "ipa": "/ˈræpɪd/", "lvl": "B2", "ctx": "Academic", "en": "Happening in a short time or at a fast pace", "vn": "Nhanh chóng", "m": "Ra rạp (rapid) nhanh", "col": "`rapid growth`: tăng trưởng nhanh", "ex1": "Rapid change.", "ex1v": "Thay đổi nhanh.", "ex2": "Rapid development.", "ex2v": "Phát triển nhanh.", "ex3": "Rapid Fire.", "ex3v": "Lửa nhanh.", "fam": "rapidity", "syn": "swift", "ant": "slow"},
    {"w": "Sluggish", "pos": "adj.", "ipa": "/ˈslʌɡɪʃ/", "lvl": "B2", "ctx": "Academic", "en": "Slow-moving or inactive", "vn": "Chậm chạp, lờ đờ", "m": "Sờ lờ mờ (sluggish) chậm", "col": "`sluggish economy`: nền kinh tế trì trệ", "ex1": "Sluggish morning.", "ex1v": "Buổi sáng lờ đờ.", "ex2": "Sluggish market.", "ex2v": "Thị trường trì trệ.", "ex3": "Sluggish feeling.", "ex3v": "Cảm giác lờ đờ.", "fam": "sluggishness", "syn": "lethargic", "ant": "brisk"},
    {"w": "Gigantic", "pos": "adj.", "ipa": "/dʒaɪˈɡæntɪk/", "lvl": "B2", "ctx": "Academic", "en": "Of very great size or extent", "vn": "Khổng lồ", "m": "Gai gan (gigantic) to lớn", "col": "`gigantic proportion`: tỷ lệ khổng lồ", "ex1": "Gigantic tree.", "ex1v": "Cây khổng lồ.", "ex2": "Gigantic task.", "ex2v": "Nhiệm vụ khổng lồ.", "ex3": "Gigantic movie.", "ex3v": "Phim khổng lồ.", "fam": "giant", "syn": "colossal", "ant": "tiny"},
    {"w": "Miniature", "pos": "adj.", "ipa": "/ˈmɪnətʃə(r)/", "lvl": "B2", "ctx": "Daily", "en": "Of a much smaller size than normal", "vn": "Thu nhỏ", "m": "Mi ni (miniature) nhỏ", "col": "`miniature model`: mô hình thu nhỏ", "ex1": "Miniature train.", "ex1v": "Tàu thu nhỏ.", "ex2": "Miniature version.", "ex2v": "Phiên bản thu nhỏ.", "ex3": "Miniature life.", "ex3v": "Cuộc sống thu nhỏ.", "fam": "mini", "syn": "small", "ant": "gigantic"},
    {"w": "Complicated", "pos": "adj.", "ipa": "/ˈkɒmplɪkeɪtɪd/", "lvl": "B2", "ctx": "Academic", "en": "Consisting of many interconnecting parts or elements", "vn": "Phức tạp", "m": "Cầm ly (complicated) cẩn thận kẻo rớt", "col": "`complicated issue`: vấn đề phức tạp", "ex1": "Complicated relationship.", "ex1v": "Mối quan hệ phức tạp.", "ex2": "Complicated process.", "ex2v": "Quy trình phức tạp.", "ex3": "It's Complicated.", "ex3v": "Chuyện tình phức tạp.", "fam": "complicate", "syn": "complex", "ant": "simple"},
    {"w": "Confused", "pos": "adj.", "ipa": "/kənˈfjuːzd/", "lvl": "B1", "ctx": "Daily", "en": "Unable to think clearly", "vn": "Bối rối", "m": "Còn phiu (confused) mờ ảo", "col": "`confused expression`: biểu cảm bối rối", "ex1": "I am confused.", "ex1v": "Tôi bối rối.", "ex2": "Confused message.", "ex2v": "Thông điệp khó hiểu.", "ex3": "Dazed and Confused.", "ex3v": "Ngơ ngác và bối rối.", "fam": "confusion", "syn": "puzzled", "ant": "clear"},
    {"w": "Exhausted", "pos": "adj.", "ipa": "/ɪɡˈzɔːstɪd/", "lvl": "B2", "ctx": "Daily", "en": "Drained of one's physical or mental resources", "vn": "Kiệt sức", "m": "Ích giọt (exhausted) cạn kiệt", "col": "`exhausted from work`: kiệt sức vì công việc", "ex1": "I am exhausted.", "ex1v": "Tôi kiệt sức.", "ex2": "Exhausted resources.", "ex2v": "Tài nguyên cạn kiệt.", "ex3": "Exhausted hero.", "ex3v": "Anh hùng kiệt sức.", "fam": "exhaustion", "syn": "tired", "ant": "energetic"},
    {"w": "Fascinating", "pos": "adj.", "ipa": "/ˈfæsɪneɪtɪŋ/", "lvl": "B2", "ctx": "Academic", "en": "Extremely interesting", "vn": "Hấp dẫn", "m": "Phát sáng (fascinating) thu hút", "col": "`fascinating subject`: chủ đề hấp dẫn", "ex1": "Fascinating story.", "ex1v": "Câu chuyện hấp dẫn.", "ex2": "Fascinating discovery.", "ex2v": "Khám phá hấp dẫn.", "ex3": "Fascinating rhythm.", "ex3v": "Nhịp điệu hấp dẫn.", "fam": "fascination", "syn": "captivating", "ant": "boring"},
    {"w": "Frightened", "pos": "adj.", "ipa": "/ˈfraɪtnd/", "lvl": "B1", "ctx": "Daily", "en": "Afraid or anxious", "vn": "Sợ hãi", "m": "Phải trốn (frightened) vì sợ", "col": "`frightened of spiders`: sợ nhện", "ex1": "Frightened child.", "ex1v": "Đứa trẻ sợ hãi.", "ex2": "Frightened state.", "ex2v": "Tình trạng sợ hãi.", "ex3": "Frighteners.", "ex3v": "Những kẻ đáng sợ.", "fam": "fright", "syn": "scared", "ant": "brave"},
    {"w": "Mysterious", "pos": "adj.", "ipa": "/mɪˈstɪəriəs/", "lvl": "B2", "ctx": "Academic", "en": "Difficult or impossible to understand, explain, or identify", "vn": "Bí ẩn", "m": "Mít tơ (mysterious) bí ẩn", "col": "`mysterious circumstances`: hoàn cảnh bí ẩn", "ex1": "Mysterious stranger.", "ex1v": "Người lạ bí ẩn.", "ex2": "Mysterious disease.", "ex2v": "Căn bệnh bí ẩn.", "ex3": "Mysterious Island.", "ex3v": "Hòn đảo bí ẩn.", "fam": "mystery", "syn": "enigmatic", "ant": "clear"},

    # C1-C2
    {"w": "Impeccable", "pos": "adj.", "ipa": "/ɪmˈpekəbl/", "lvl": "C1", "ctx": "Formal", "en": "In accordance with the highest standards; faultless", "vn": "Hoàn hảo, không tì vết", "m": "Im (không) rách (peccable)", "col": "`impeccable timing`: thời điểm hoàn hảo", "ex1": "Impeccable manners.", "ex1v": "Cư xử hoàn hảo.", "ex2": "Impeccable academic record.", "ex2v": "Thành tích học tập không tì vết.", "ex3": "Impeccable taste.", "ex3v": "Gu thẩm mỹ hoàn hảo.", "fam": "impeccably", "syn": "flawless", "ant": "flawed"},
    {"w": "Atrocious", "pos": "adj.", "ipa": "/əˈtrəʊʃəs/", "lvl": "C2", "ctx": "Formal", "en": "Horrifyingly wicked", "vn": "Tàn bạo, kinh khủng", "m": "A trấu (atrocious) kinh khủng", "col": "`atrocious behavior`: hành vi tồi tệ", "ex1": "Atrocious weather.", "ex1v": "Thời tiết kinh khủng.", "ex2": "Atrocious crime.", "ex2v": "Tội ác tàn bạo.", "ex3": "Atrocious acts.", "ex3v": "Hành động tàn bạo.", "fam": "atrocity", "syn": "appalling", "ant": "magnificent"},
    {"w": "Colossal", "pos": "adj.", "ipa": "/kəˈlɒsl/", "lvl": "C1", "ctx": "Academic", "en": "Extremely large", "vn": "Khổng lồ", "m": "Cổ lỗ sĩ (colossal) khổng lồ", "col": "`colossal amount`: số lượng khổng lồ", "ex1": "Colossal mistake.", "ex1v": "Sai lầm khổng lồ.", "ex2": "Colossal failure.", "ex2v": "Thất bại khổng lồ.", "ex3": "Colossal Titan.", "ex3v": "Titan khổng lồ.", "fam": "colossus", "syn": "immense", "ant": "tiny"},
    {"w": "Infinitesimal", "pos": "adj.", "ipa": "/ˌɪnfɪnɪˈtesɪml/", "lvl": "C2", "ctx": "Academic", "en": "Extremely small", "vn": "Cực kì nhỏ", "m": "In phin (infinitesimal) nhỏ vô cực", "col": "`infinitesimal change`: sự thay đổi cực nhỏ", "ex1": "Infinitesimal pause.", "ex1v": "Quãng nghỉ cực nhỏ.", "ex2": "Infinitesimal traces.", "ex2v": "Dấu vết cực nhỏ.", "ex3": "Infinitesimal point.", "ex3v": "Điểm cực nhỏ.", "fam": "infinitesimally", "syn": "minute", "ant": "huge"},
    {"w": "Frigid", "pos": "adj.", "ipa": "/ˈfrɪdʒɪd/", "lvl": "C1", "ctx": "Formal", "en": "Very cold in temperature", "vn": "Lạnh giá", "m": "Free (lạnh) giọt (frigid)", "col": "`frigid climate`: khí hậu lạnh giá", "ex1": "Frigid air.", "ex1v": "Không khí lạnh giá.", "ex2": "Frigid relations.", "ex2v": "Mối quan hệ lạnh nhạt.", "ex3": "Frigid zone.", "ex3v": "Vùng giá lạnh.", "fam": "frigidity", "syn": "freezing", "ant": "hot"},
    {"w": "Sweltering", "pos": "adj.", "ipa": "/ˈsweltərɪŋ/", "lvl": "C1", "ctx": "Formal", "en": "Uncomfortably hot", "vn": "Nóng ngột ngạt", "m": "Sờ veo (sweltering) mồ hôi vì nóng", "col": "`sweltering heat`: cái nóng ngột ngạt", "ex1": "Sweltering day.", "ex1v": "Ngày nóng ngột ngạt.", "ex2": "Sweltering conditions.", "ex2v": "Điều kiện nóng nực.", "ex3": "Sweltering room.", "ex3v": "Căn phòng nóng bức.", "fam": "swelter", "syn": "boiling", "ant": "freezing"},
    {"w": "Ecstatic", "pos": "adj.", "ipa": "/ɪkˈstætɪk/", "lvl": "C1", "ctx": "Formal", "en": "Feeling or expressing overwhelming happiness", "vn": "Vô cùng hạnh phúc", "m": "Éc tắc (ecstatic) vì vui sướng", "col": "`ecstatic fans`: người hâm mộ cuồng nhiệt", "ex1": "Ecstatic joy.", "ex1v": "Niềm vui sướng tột độ.", "ex2": "Ecstatic review.", "ex2v": "Đánh giá tuyệt vời.", "ex3": "Ecstatic dance.", "ex3v": "Điệu nhảy hoan hỉ.", "fam": "ecstasy", "syn": "overjoyed", "ant": "miserable"},
    {"w": "Despondent", "pos": "adj.", "ipa": "/dɪˈspɒndənt/", "lvl": "C2", "ctx": "Academic", "en": "In low spirits from loss of hope or courage", "vn": "Chán nản, tuyệt vọng", "m": "Đề sờ (despondent) vì chán", "col": "`despondent mood`: tâm trạng chán nản", "ex1": "He looked despondent.", "ex1v": "Anh ấy trông tuyệt vọng.", "ex2": "Despondent youth.", "ex2v": "Giới trẻ chán nản.", "ex3": "Despondent hero.", "ex3v": "Anh hùng tuyệt vọng.", "fam": "despondency", "syn": "disheartened", "ant": "hopeful"},
    {"w": "Resplendent", "pos": "adj.", "ipa": "/rɪˈsplendənt/", "lvl": "C2", "ctx": "Formal", "en": "Attractive and impressive through being richly colorful", "vn": "Rực rỡ, chói lọi", "m": "Rẽ sờ (resplendent) thấy sáng rực", "col": "`resplendent beauty`: vẻ đẹp rực rỡ", "ex1": "Resplendent dress.", "ex1v": "Chiếc váy rực rỡ.", "ex2": "Resplendent architecture.", "ex2v": "Kiến trúc tráng lệ.", "ex3": "Resplendent sun.", "ex3v": "Mặt trời chói lọi.", "fam": "resplendence", "syn": "dazzling", "ant": "dull"},
    {"w": "Grotesque", "pos": "adj.", "ipa": "/ɡrəʊˈtesk/", "lvl": "C1", "ctx": "Academic", "en": "Comically or repulsively ugly or distorted", "vn": "Kỳ cục, lố bịch", "m": "Gờ rô (grotesque) kỳ cục", "col": "`grotesque distortion`: sự bóp méo kỳ cục", "ex1": "Grotesque face.", "ex1v": "Khuôn mặt lố bịch.", "ex2": "Grotesque inequality.", "ex2v": "Sự bất bình đẳng lố bịch.", "ex3": "Grotesque monster.", "ex3v": "Quái vật kỳ dị.", "fam": "grotesqueness", "syn": "malformed", "ant": "normal"},
    {"w": "Expeditious", "pos": "adj.", "ipa": "/ˌekspəˈdɪʃəs/", "lvl": "C2", "ctx": "Formal", "en": "Done with speed and efficiency", "vn": "Nhanh chóng, mau lẹ", "m": "Ép xe đi (expeditious) nhanh", "col": "`expeditious manner`: cách nhanh chóng", "ex1": "Expeditious delivery.", "ex1v": "Giao hàng mau lẹ.", "ex2": "Expeditious process.", "ex2v": "Quy trình nhanh chóng.", "ex3": "Expeditious retreat.", "ex3v": "Rút lui nhanh chóng.", "fam": "expedition", "syn": "speedy", "ant": "slow"},
    {"w": "Lethargic", "pos": "adj.", "ipa": "/ləˈθɑːdʒɪk/", "lvl": "C1", "ctx": "Academic", "en": "Affected by lethargy; sluggish and apathetic", "vn": "Lờ đờ, uể oải", "m": "Lê thê (lethargic) mệt mỏi", "col": "`lethargic state`: trạng thái lờ đờ", "ex1": "Feel lethargic.", "ex1v": "Cảm thấy uể oải.", "ex2": "Lethargic response.", "ex2v": "Phản hồi chậm chạp.", "ex3": "Lethargic patient.", "ex3v": "Bệnh nhân lờ đờ.", "fam": "lethargy", "syn": "sluggish", "ant": "energetic"},
    {"w": "Gargantuan", "pos": "adj.", "ipa": "/ɡɑːˈɡæntʃuən/", "lvl": "C1", "ctx": "Formal", "en": "Enormous", "vn": "Khổng lồ, to lớn", "m": "Gà gáy to (gargantuan)", "col": "`gargantuan appetite`: sự thèm ăn khổng lồ", "ex1": "Gargantuan meal.", "ex1v": "Bữa ăn khổng lồ.", "ex2": "Gargantuan effort.", "ex2v": "Nỗ lực to lớn.", "ex3": "Gargantuan beast.", "ex3v": "Quái thú khổng lồ.", "fam": "gargantua", "syn": "massive", "ant": "tiny"},
    {"w": "Microscopic", "pos": "adj.", "ipa": "/ˌmaɪkrəˈskɒpɪk/", "lvl": "C1", "ctx": "Academic", "en": "So small as to be visible only with a microscope", "vn": "Siêu nhỏ, vi mô", "m": "Vi mô (micro) nhỏ", "col": "`microscopic level`: cấp độ vi mô", "ex1": "Microscopic dust.", "ex1v": "Bụi siêu nhỏ.", "ex2": "Microscopic analysis.", "ex2v": "Phân tích vi mô.", "ex3": "Microscopic organisms.", "ex3v": "Sinh vật vi mô.", "fam": "microscope", "syn": "minuscule", "ant": "macroscopic"},
    {"w": "Convoluted", "pos": "adj.", "ipa": "/ˈkɒnvəluːtɪd/", "lvl": "C1", "ctx": "Academic", "en": "Extremely complex and difficult to follow", "vn": "Phức tạp, rối rắm", "m": "Còn vô (convoluted) lộn xộn", "col": "`convoluted plot`: cốt truyện rắc rối", "ex1": "Convoluted excuse.", "ex1v": "Lời bào chữa vòng vo.", "ex2": "Convoluted theory.", "ex2v": "Lý thuyết phức tạp.", "ex3": "Convoluted storyline.", "ex3v": "Cốt truyện rối rắm.", "fam": "convolution", "syn": "intricate", "ant": "straightforward"}
]

# Total is 15 + 20 + 15 = 50. Let's make sure they sum to 50.
# A1: 15
# B1-B2: 20
# C1-C2: 15

# Oh wait, we only have 20 for B1/B2 but let's make sure I count them.
# A1: Good, Bad, Big, Small, Hot, Cold, Happy, Sad, Fast, Slow, Tall, Short, Easy, Hard, New (15)
# B1/B2: Amazing, Awful, Enormous, Tiny, Freezing, Boiling, Delighted, Miserable, Gorgeous, Hideous, Rapid, Sluggish, Gigantic, Miniature, Complicated, Confused, Exhausted, Fascinating, Frightened, Mysterious (20)
# C1/C2: Impeccable, Atrocious, Colossal, Infinitesimal, Frigid, Sweltering, Ecstatic, Despondent, Resplendent, Grotesque, Expeditious, Lethargic, Gargantuan, Microscopic, Convoluted (15)
# Total = 50.

template = """# {w}
*{pos}*
> {ipa}

---
**Level:** {lvl} | **Ngữ cảnh:** {ctx} | **Chủ đề:** ADJECTIVES

## 📌 Ý nghĩa (Meaning)
- **EN:** {en}
- **VN:** {vn}

## 🧠 Mẹo nhớ (Mnemonics)
💡 {m}

## 🧩 Cụm từ thường đi kèm (Collocations)
- `{col}`

## 🎬 Ví dụ thực tế (Real-world Examples)
1. 💬 *Daily:* {ex1}
   *-> {ex1v}*
2. 💼 *Work/Academic:* {ex2}
   *-> {ex2v}*
3. 🎬 *Media/Movie:* {ex3}
   *-> {ex3v}*

## 🕸️ Mạng lưới từ (Word Network)
**Word Family:**
- {fam}

**Synonyms:** {syn}
**Antonyms:** {ant}
"""

out_dir = "/home/thinh/Documents/Obsidian Vault/English/Vocabulary Topics/1. Basic Concepts & Grammar/ADJECTIVES"

for item in data:
    content = template.format(**item)
    file_path = os.path.join(out_dir, f"{item['w']}.md")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
print(f"Successfully generated {len(data)} vocabulary files in {out_dir}")
