import os

target_dir = "/home/thinh/Documents/Obsidian Vault/English/Vocabulary Topics/1. Basic Concepts & Grammar/TIME"
os.makedirs(target_dir, exist_ok=True)

words = [
    # A1-A2
    {"w":"Day","pos":"n.","ipa":"/deɪ/","lvl":"A1","ctx":"Daily","en":"A period of 24 hours","vn":"Ngày","m":"Day -> Đây: Nơi đây ngày trôi qua nhanh","col1":"day off","vn1":"ngày nghỉ","ex1":"What day is it today?","ex1v":"Hôm nay là ngày mấy?","ex2":"Working days are Monday to Friday.","ex2v":"Ngày làm việc là thứ Hai đến thứ Sáu.","ex3":"Day after day, he waits.","ex3v":"Ngày qua ngày, anh ấy chờ đợi.","fam":"daily (adj.)","syn":"daytime","ant":"night"},
    {"w":"Night","pos":"n.","ipa":"/naɪt/","lvl":"A1","ctx":"Daily","en":"The period of darkness between sunset and sunrise","vn":"Đêm","m":"Night -> Nai: Con nai chạy trong đêm","col1":"at night","vn1":"vào ban đêm","ex1":"I sleep at night.","ex1v":"Tôi ngủ vào ban đêm.","ex2":"Night shifts are tiring.","ex2v":"Ca đêm rất mệt mỏi.","ex3":"The night is dark and full of terrors.","ex3v":"Đêm tối và đầy rẫy nỗi kinh hoàng.","fam":"nightly (adj.)","syn":"evening","ant":"day"},
    {"w":"Week","pos":"n.","ipa":"/wiːk/","lvl":"A1","ctx":"Daily","en":"A period of seven days","vn":"Tuần","m":"Week -> Quýt: Cả tuần ăn quýt","col1":"last week","vn1":"tuần trước","ex1":"See you next week.","ex1v":"Hẹn gặp bạn tuần sau.","ex2":"We have a weekly meeting.","ex2v":"Chúng ta có cuộc họp hàng tuần.","ex3":"A week has passed.","ex3v":"Một tuần đã trôi qua.","fam":"weekly (adj.)","syn":"seven days","ant":"N/A"},
    {"w":"Month","pos":"n.","ipa":"/mʌnθ/","lvl":"A1","ctx":"Daily","en":"A period of about four weeks","vn":"Tháng","m":"Month -> Mân: Mân mê cuốn lịch cả tháng","col1":"next month","vn1":"tháng sau","ex1":"My birthday is this month.","ex1v":"Sinh nhật tôi vào tháng này.","ex2":"Monthly reports are due.","ex2v":"Báo cáo hàng tháng đến hạn.","ex3":"It took a month to film.","ex3v":"Mất một tháng để quay phim.","fam":"monthly (adj.)","syn":"N/A","ant":"N/A"},
    {"w":"Year","pos":"n.","ipa":"/jɪər/","lvl":"A1","ctx":"Daily","en":"A period of 365 or 366 days","vn":"Năm","m":"Year -> Bia: Uống bia cả năm","col1":"leap year","vn1":"năm nhuận","ex1":"Happy New Year!","ex1v":"Chúc mừng năm mới!","ex2":"Annual revenue increased this year.","ex2v":"Doanh thu hàng năm tăng trong năm nay.","ex3":"A year of changes.","ex3v":"Một năm của những thay đổi.","fam":"yearly (adj.)","syn":"annum","ant":"N/A"},
    {"w":"Hour","pos":"n.","ipa":"/aʊər/","lvl":"A1","ctx":"Daily","en":"A period of 60 minutes","vn":"Giờ","m":"Hour -> Ao: Đứng chờ bên ao cả giờ","col1":"half an hour","vn1":"nửa giờ","ex1":"I will be there in an hour.","ex1v":"Tôi sẽ đến đó trong một giờ nữa.","ex2":"Billable hours are tracked.","ex2v":"Số giờ tính phí được theo dõi.","ex3":"The zero hour approaches.","ex3v":"Giờ G đang đến gần.","fam":"hourly (adj.)","syn":"60 minutes","ant":"N/A"},
    {"w":"Minute","pos":"n.","ipa":"/ˈmɪnɪt/","lvl":"A1","ctx":"Daily","en":"A period of 60 seconds","vn":"Phút","m":"Minute -> Mi nứt: Bánh mì nứt ra trong vài phút","col1":"wait a minute","vn1":"chờ một chút","ex1":"Give me a minute.","ex1v":"Cho tôi một phút.","ex2":"Take the minutes of the meeting.","ex2v":"Ghi biên bản cuộc họp (từ đồng âm).","ex3":"Just a minute, please!","ex3v":"Xin đợi một phút!","fam":"minutely (adv.)","syn":"moment","ant":"N/A"},
    {"w":"Second","pos":"n.","ipa":"/ˈsekənd/","lvl":"A1","ctx":"Daily","en":"1/60th of a minute","vn":"Giây","m":"Second -> Xe cần: Xe cần vài giây để khởi động","col1":"in a second","vn1":"trong một giây","ex1":"I'll be ready in a second.","ex1v":"Tôi sẽ sẵn sàng trong một giây.","ex2":"Every second counts in the exam.","ex2v":"Mỗi giây đều quan trọng trong kỳ thi.","ex3":"Split second decision.","ex3v":"Quyết định trong tích tắc.","fam":"secondly (adv.)","syn":"instant","ant":"N/A"},
    {"w":"Morning","pos":"n.","ipa":"/ˈmɔːnɪŋ/","lvl":"A1","ctx":"Daily","en":"The early part of the day","vn":"Buổi sáng","m":"Morning -> Mo ninh: Cảnh báo (warning) buổi sáng","col1":"good morning","vn1":"chào buổi sáng","ex1":"I run every morning.","ex1v":"Tôi chạy bộ mỗi sáng.","ex2":"Morning shifts start at 8.","ex2v":"Ca sáng bắt đầu lúc 8 giờ.","ex3":"Morning has broken.","ex3v":"Buổi sáng đã đến.","fam":"N/A","syn":"dawn","ant":"evening"},
    {"w":"Afternoon","pos":"n.","ipa":"/ˌɑːftəˈnuːn/","lvl":"A1","ctx":"Daily","en":"The time from noon until evening","vn":"Buổi chiều","m":"Afternoon -> Áp tơ: Áp lực công việc buổi chiều","col1":"in the afternoon","vn1":"vào buổi chiều","ex1":"Let's meet this afternoon.","ex1v":"Hãy gặp nhau chiều nay.","ex2":"The afternoon session is canceled.","ex2v":"Phiên họp buổi chiều bị hủy.","ex3":"A quiet Sunday afternoon.","ex3v":"Một buổi chiều Chủ nhật yên tĩnh.","fam":"N/A","syn":"post-meridiem","ant":"morning"},
    {"w":"Evening","pos":"n.","ipa":"/ˈiːvnɪŋ/","lvl":"A1","ctx":"Daily","en":"The latter part of the day, before night","vn":"Buổi tối","m":"Evening -> Yêu vì: Yêu vì những buổi tối lãng mạn","col1":"evening dress","vn1":"váy dạ hội (buổi tối)","ex1":"What are you doing this evening?","ex1v":"Bạn làm gì tối nay?","ex2":"Evening classes are available.","ex2v":"Có các lớp học buổi tối.","ex3":"A pleasant evening.","ex3v":"Một buổi tối dễ chịu.","fam":"N/A","syn":"dusk","ant":"morning"},
    {"w":"Today","pos":"n./adv.","ipa":"/təˈdeɪ/","lvl":"A1","ctx":"Daily","en":"This present day","vn":"Hôm nay","m":"Today -> Tớ đây: Tớ đây, hôm nay tớ đã đến","col1":"today's news","vn1":"tin tức hôm nay","ex1":"Today is Monday.","ex1v":"Hôm nay là thứ Hai.","ex2":"The deadline is today.","ex2v":"Hạn chót là hôm nay.","ex3":"Today is the day!","ex3v":"Hôm nay chính là ngày đó!","fam":"N/A","syn":"nowadays","ant":"yesterday"},
    {"w":"Tomorrow","pos":"n./adv.","ipa":"/təˈmɒrəʊ/","lvl":"A1","ctx":"Daily","en":"The day after today","vn":"Ngày mai","m":"Tomorrow -> Tơ mò: Mờ sáng tơ mò ngày mai","col1":"see you tomorrow","vn1":"hẹn gặp ngày mai","ex1":"I will go tomorrow.","ex1v":"Tôi sẽ đi vào ngày mai.","ex2":"Tomorrow's agenda is full.","ex2v":"Lịch trình ngày mai đã kín.","ex3":"Tomorrow never dies.","ex3v":"Ngày mai không bao giờ chết.","fam":"N/A","syn":"the next day","ant":"yesterday"},
    {"w":"Yesterday","pos":"n./adv.","ipa":"/ˈjestədeɪ/","lvl":"A1","ctx":"Daily","en":"The day before today","vn":"Hôm qua","m":"Yesterday -> Ghét tơ: Ghét tơ vương từ ngày hôm qua","col1":"yesterday morning","vn1":"sáng hôm qua","ex1":"I saw him yesterday.","ex1v":"Tôi đã gặp anh ấy hôm qua.","ex2":"Yesterday's meeting was productive.","ex2v":"Cuộc họp hôm qua rất hiệu quả.","ex3":"Yesterday, all my troubles seemed so far away.","ex3v":"Hôm qua, mọi rắc rối dường như đã lùi xa.","fam":"N/A","syn":"the previous day","ant":"tomorrow"},
    {"w":"Clock","pos":"n.","ipa":"/klɒk/","lvl":"A1","ctx":"Daily","en":"An instrument for measuring and showing time","vn":"Đồng hồ (treo tường/để bàn)","m":"Clock -> Lọc: Lọc tiếng tích tắc của đồng hồ","col1":"alarm clock","vn1":"đồng hồ báo thức","ex1":"Look at the clock.","ex1v":"Hãy nhìn đồng hồ kìa.","ex2":"Clock in at 9 AM.","ex2v":"Chấm công lúc 9 giờ sáng.","ex3":"The clock is ticking.","ex3v":"Đồng hồ đang điểm (Thời gian không còn nhiều).","fam":"clockwise (adv.)","syn":"watch","ant":"N/A"},

    # B1-B2
    {"w":"Decade","pos":"n.","ipa":"/ˈdekeɪd/","lvl":"B1","ctx":"Academic","en":"A period of ten years","vn":"Thập kỷ","m":"Decade -> Đế cày: Cày cuốc cả thập kỷ để lên ngôi đế","col1":"a decade ago","vn1":"một thập kỷ trước","ex1":"I haven't seen her for a decade.","ex1v":"Tôi đã không gặp cô ấy cả thập kỷ rồi.","ex2":"Economic growth over the last decade.","ex2v":"Tăng trưởng kinh tế trong thập kỷ qua.","ex3":"The defining movie of the decade.","ex3v":"Bộ phim tiêu biểu của thập kỷ.","fam":"decadal (adj.)","syn":"ten years","ant":"N/A"},
    {"w":"Century","pos":"n.","ipa":"/ˈsentʃəri/","lvl":"B1","ctx":"Academic","en":"A period of 100 years","vn":"Thế kỷ","m":"Century -> Sen chửa: Cây sen chửa ra hoa sau một thế kỷ","col1":"21st century","vn1":"thế kỷ 21","ex1":"We live in the 21st century.","ex1v":"Chúng ta sống ở thế kỷ 21.","ex2":"A century of technological advancement.","ex2v":"Một thế kỷ của tiến bộ công nghệ.","ex3":"The crime of the century.","ex3v":"Tội ác của thế kỷ.","fam":"centennial (adj.)","syn":"100 years","ant":"N/A"},
    {"w":"Millennium","pos":"n.","ipa":"/mɪˈleniəm/","lvl":"B2","ctx":"Academic","en":"A period of 1000 years","vn":"Thiên niên kỷ","m":"Millennium -> Mi lên ni: Mi lên nương một thiên niên kỷ mới xuống","col1":"new millennium","vn1":"thiên niên kỷ mới","ex1":"We celebrated the new millennium.","ex1v":"Chúng tôi đã ăn mừng thiên niên kỷ mới.","ex2":"Millennium development goals.","ex2v":"Các mục tiêu phát triển thiên niên kỷ.","ex3":"The Millennium Falcon.","ex3v":"Tàu Millennium Falcon.","fam":"millennial (n./adj.)","syn":"1000 years","ant":"N/A"},
    {"w":"Schedule","pos":"n./v.","ipa":"/ˈʃedjuːl/","lvl":"B1","ctx":"Work","en":"A plan of times for tasks or events","vn":"Lịch trình, lên lịch","m":"Schedule -> Sẽ đều: Mọi việc sẽ đều đặn theo lịch trình","col1":"on schedule","vn1":"đúng lịch trình","ex1":"My schedule is full today.","ex1v":"Lịch trình của tôi hôm nay đã kín.","ex2":"The project is running behind schedule.","ex2v":"Dự án đang chậm tiến độ.","ex3":"Let's schedule a meeting.","ex3v":"Hãy lên lịch một cuộc họp.","fam":"scheduled (adj.)","syn":"timetable","ant":"N/A"},
    {"w":"Deadline","pos":"n.","ipa":"/ˈdedlaɪn/","lvl":"B1","ctx":"Work","en":"The latest time or date by which something should be completed","vn":"Hạn chót","m":"Deadline -> Đét lai: Quá hạn chót là bị đét đòn","col1":"meet a deadline","vn1":"kịp hạn chót","ex1":"The deadline is tomorrow.","ex1v":"Hạn chót là ngày mai.","ex2":"We must meet the project deadline.","ex2v":"Chúng ta phải hoàn thành đúng hạn chót dự án.","ex3":"Approaching the deadline.","ex3v":"Đang đến gần hạn chót.","fam":"N/A","syn":"time limit","ant":"N/A"},
    {"w":"Punctual","pos":"adj.","ipa":"/ˈpʌŋktʃuəl/","lvl":"B1","ctx":"Daily","en":"Happening or doing something at the agreed or proper time","vn":"Đúng giờ","m":"Punctual -> Bắn chua: Bắn cung chua ngoa nhưng rất đúng giờ","col1":"punctual arrival","vn1":"đến đúng giờ","ex1":"Please be punctual for dinner.","ex1v":"Vui lòng đến đúng giờ ăn tối.","ex2":"Punctuality is expected in the workplace.","ex2v":"Việc đúng giờ được mong đợi ở nơi làm việc.","ex3":"He is always punctual.","ex3v":"Anh ấy luôn đúng giờ.","fam":"punctuality (n.)","syn":"on time","ant":"late"},
    {"w":"Delay","pos":"n./v.","ipa":"/dɪˈleɪ/","lvl":"B1","ctx":"Work","en":"Make someone or something late or slow","vn":"Trì hoãn, sự chậm trễ","m":"Delay -> Đi lầy: Đi qua chỗ lầy nên bị trì hoãn","col1":"without delay","vn1":"không chậm trễ","ex1":"The train was delayed.","ex1v":"Chuyến tàu bị hoãn.","ex2":"Any delay will cost us money.","ex2v":"Bất kỳ sự chậm trễ nào cũng sẽ làm chúng ta tốn tiền.","ex3":"Sorry for the delay.","ex3v":"Xin lỗi vì sự chậm trễ.","fam":"delayed (adj.)","syn":"postpone","ant":"rush"},
    {"w":"Duration","pos":"n.","ipa":"/djuˈreɪʃn/","lvl":"B2","ctx":"Academic","en":"The time during which something continues","vn":"Khoảng thời gian, thời lượng","m":"Duration -> Du rê: Du khách rê chân một khoảng thời gian dài","col1":"for the duration of","vn1":"trong suốt khoảng thời gian của","ex1":"The duration of the movie is 2 hours.","ex1v":"Thời lượng của bộ phim là 2 giờ.","ex2":"The contract is valid for a duration of one year.","ex2v":"Hợp đồng có hiệu lực trong khoảng thời gian một năm.","ex3":"Flight duration is short.","ex3v":"Thời gian bay ngắn.","fam":"durable (adj.)","syn":"period","ant":"N/A"},
    {"w":"Frequent","pos":"adj.","ipa":"/ˈfriːkwənt/","lvl":"B1","ctx":"Daily","en":"Occurring or done many times at short intervals","vn":"Thường xuyên","m":"Frequent -> Free quần: Nhận free quần áo thường xuyên","col1":"frequent visitor","vn1":"khách ghé thăm thường xuyên","ex1":"I am a frequent traveler.","ex1v":"Tôi là người đi du lịch thường xuyên.","ex2":"Frequent updates are required.","ex2v":"Yêu cầu cập nhật thường xuyên.","ex3":"He suffers from frequent headaches.","ex3v":"Anh ấy bị đau đầu thường xuyên.","fam":"frequency (n.)","syn":"regular","ant":"rare"},
    {"w":"Rarely","pos":"adv.","ipa":"/ˈreəli/","lvl":"B1","ctx":"Daily","en":"Not often; seldom","vn":"Hiếm khi","m":"Rarely -> Rẻ rề: Đồ rẻ rề hiếm khi tốt","col1":"rarely happen","vn1":"hiếm khi xảy ra","ex1":"I rarely eat fast food.","ex1v":"Tôi hiếm khi ăn đồ ăn nhanh.","ex2":"Such cases are rarely seen in practice.","ex2v":"Những trường hợp như vậy hiếm khi thấy trong thực tế.","ex3":"He rarely speaks.","ex3v":"Anh ta hiếm khi nói chuyện.","fam":"rare (adj.)","syn":"seldom","ant":"frequently"},
    {"w":"Timetable","pos":"n.","ipa":"/ˈtaɪmteɪbl/","lvl":"B1","ctx":"Daily","en":"A chart showing the times at which events will happen","vn":"Thời khóa biểu, lịch trình","m":"Time + table = bảng thời gian","col1":"bus timetable","vn1":"lịch trình xe buýt","ex1":"Check the bus timetable.","ex1v":"Kiểm tra lịch trình xe buýt.","ex2":"The project timetable is strict.","ex2v":"Lịch trình dự án rất nghiêm ngặt.","ex3":"According to the timetable.","ex3v":"Theo như thời khóa biểu.","fam":"N/A","syn":"schedule","ant":"N/A"},
    {"w":"Postpone","pos":"v.","ipa":"/pəˈspəʊn/","lvl":"B1","ctx":"Work","en":"Cause or arrange for something to take place at a time later than that first scheduled","vn":"Trì hoãn, hoãn lại","m":"Postpone -> Bớt bôn: Bớt bôn ba, hoãn chuyến đi lại","col1":"postpone a meeting","vn1":"hoãn cuộc họp","ex1":"They postponed the game because of rain.","ex1v":"Họ đã hoãn trận đấu vì trời mưa.","ex2":"The board decided to postpone the vote.","ex2v":"Ban quản trị quyết định hoãn cuộc bỏ phiếu.","ex3":"Don't postpone joy.","ex3v":"Đừng trì hoãn niềm vui.","fam":"postponement (n.)","syn":"delay","ant":"advance"},
    {"w":"Annual","pos":"adj.","ipa":"/ˈænjuəl/","lvl":"B1","ctx":"Work","en":"Occurring once a year","vn":"Hàng năm","m":"Annual -> Ăn nụ: Cây này mỗi năm cho ăn nụ một lần","col1":"annual report","vn1":"báo cáo thường niên","ex1":"This is an annual event.","ex1v":"Đây là một sự kiện hàng năm.","ex2":"The company's annual revenue grew.","ex2v":"Doanh thu hàng năm của công ty đã tăng.","ex3":"Annual leave is 14 days.","ex3v":"Nghỉ phép hàng năm là 14 ngày.","fam":"annually (adv.)","syn":"yearly","ant":"N/A"},
    {"w":"Routine","pos":"n./adj.","ipa":"/ruːˈtiːn/","lvl":"B1","ctx":"Daily","en":"A sequence of actions regularly followed; a fixed program","vn":"Thói quen, thường lệ","m":"Routine -> Ru con: Việc ru con ngủ là thói quen hàng ngày","col1":"daily routine","vn1":"thói quen hàng ngày","ex1":"My morning routine includes coffee.","ex1v":"Thói quen buổi sáng của tôi bao gồm cà phê.","ex2":"This is just a routine inspection.","ex2v":"Đây chỉ là một cuộc kiểm tra thường lệ.","ex3":"A break from routine.","ex3v":"Một sự phá vỡ thói quen.","fam":"routinely (adv.)","syn":"habit","ant":"N/A"},
    {"w":"Temporary","pos":"adj.","ipa":"/ˈtemprəri/","lvl":"B1","ctx":"Work","en":"Lasting for only a limited period of time; not permanent","vn":"Tạm thời","m":"Temporary -> Đem bỏ ri: Đồ tạm thời xài xong đem bỏ đi","col1":"temporary job","vn1":"công việc tạm thời","ex1":"This is a temporary solution.","ex1v":"Đây là một giải pháp tạm thời.","ex2":"We hired temporary staff for the holiday season.","ex2v":"Chúng tôi đã thuê nhân viên tạm thời cho mùa lễ.","ex3":"Temporary memory loss.","ex3v":"Mất trí nhớ tạm thời.","fam":"temporarily (adv.)","syn":"provisional","ant":"permanent"},
    {"w":"Permanent","pos":"adj.","ipa":"/ˈpɜːmənənt/","lvl":"B2","ctx":"Work","en":"Lasting or intended to last or remain unchanged indefinitely","vn":"Vĩnh viễn, lâu dài","m":"Permanent -> Bơ mà nặn: Đồ bơ mà nặn thì không thể vĩnh viễn được","col1":"permanent address","vn1":"địa chỉ thường trú","ex1":"I am looking for a permanent job.","ex1v":"Tôi đang tìm một công việc lâu dài.","ex2":"The ink causes permanent stains.","ex2v":"Mực gây ra vết ố vĩnh viễn.","ex3":"Permanent marker.","ex3v":"Bút lông viết không xóa được.","fam":"permanently (adv.)","syn":"lasting","ant":"temporary"},
    {"w":"Occasion","pos":"n.","ipa":"/əˈkeɪʒn/","lvl":"B1","ctx":"Daily","en":"A particular time or instance of an event","vn":"Dịp, cơ hội","m":"Occasion -> Ếch kêu sân: Dịp ếch kêu ngoài sân là lúc trời mưa","col1":"special occasion","vn1":"dịp đặc biệt","ex1":"I wear this dress on special occasions.","ex1v":"Tôi mặc chiếc váy này vào những dịp đặc biệt.","ex2":"The occasion calls for formal attire.","ex2v":"Dịp này yêu cầu trang phục trang trọng.","ex3":"A memorable occasion.","ex3v":"Một dịp đáng nhớ.","fam":"occasional (adj.)","syn":"event","ant":"N/A"},
    {"w":"Period","pos":"n.","ipa":"/ˈpɪəriəd/","lvl":"B1","ctx":"Academic","en":"A length or portion of time","vn":"Thời kỳ, giai đoạn","m":"Period -> Bia rỉ: Giai đoạn này bia rỉ ra liên tục","col1":"a period of time","vn1":"một khoảng thời gian","ex1":"It was a difficult period.","ex1v":"Đó là một giai đoạn khó khăn.","ex2":"Sales increased over a six-month period.","ex2v":"Doanh thu tăng trong khoảng thời gian sáu tháng.","ex3":"The Jurassic period.","ex3v":"Kỷ Jura.","fam":"periodic (adj.)","syn":"time","ant":"N/A"},
    {"w":"Interval","pos":"n.","ipa":"/ˈɪntəvl/","lvl":"B2","ctx":"Academic","en":"An intervening time or space","vn":"Khoảng thời gian (giữa hai sự kiện)","m":"Interval -> In tờ vé: Trong khoảng thời gian nghỉ, đi in tờ vé","col1":"regular intervals","vn1":"những khoảng thời gian đều đặn","ex1":"There will be a 15-minute interval.","ex1v":"Sẽ có 15 phút giải lao.","ex2":"Trains leave at regular intervals.","ex2v":"Tàu khởi hành vào những khoảng thời gian đều đặn.","ex3":"An interval of silence.","ex3v":"Một khoảng lặng.","fam":"N/A","syn":"gap","ant":"N/A"},
    {"w":"Prior","pos":"adj.","ipa":"/ˈpraɪər/","lvl":"B2","ctx":"Work","en":"Existing or coming before in time, order, or importance","vn":"Trước","m":"Prior -> Phải lo: Việc trước mắt phải lo","col1":"prior to","vn1":"trước khi","ex1":"I have a prior engagement.","ex1v":"Tôi có một cuộc hẹn trước.","ex2":"Prior knowledge is required.","ex2v":"Yêu cầu kiến thức từ trước.","ex3":"Prior notice.","ex3v":"Thông báo trước.","fam":"priority (n.)","syn":"previous","ant":"subsequent"},

    # C1-C2
    {"w":"Chronological","pos":"adj.","ipa":"/ˌkrɒnəˈlɒdʒɪkl/","lvl":"C1","ctx":"Academic","en":"Relating to the establishment of dates and time sequences","vn":"Theo trình tự thời gian","m":"Chrono (thời gian) + logical (logic) = logic thời gian","col1":"chronological order","vn1":"theo trình tự thời gian","ex1":"List your jobs in chronological order.","ex1v":"Liệt kê các công việc của bạn theo trình tự thời gian.","ex2":"The history book presents events in a chronological sequence.","ex2v":"Cuốn sách lịch sử trình bày các sự kiện theo một trình tự thời gian.","ex3":"A chronological timeline of the universe.","ex3v":"Dòng thời gian của vũ trụ.","fam":"chronologically (adv.)","syn":"sequential","ant":"random"},
    {"w":"Ephemeral","pos":"adj.","ipa":"/ɪˈfemərəl/","lvl":"C2","ctx":"Academic","en":"Lasting for a very short time","vn":"Phù du, chóng tàn","m":"Ephemeral -> Ép em rứa: Ép em rứa thì tình cảm cũng phù du thôi","col1":"ephemeral nature","vn1":"bản chất phù du","ex1":"Fame is ephemeral.","ex1v":"Danh tiếng là phù du.","ex2":"The ephemeral nature of fashion trends.","ex2v":"Tính chất sớm nở tối tàn của các xu hướng thời trang.","ex3":"Ephemeral joy.","ex3v":"Niềm vui ngắn ngủi.","fam":"ephemerally (adv.)","syn":"transient","ant":"permanent"},
    {"w":"Fleeting","pos":"adj.","ipa":"/ˈfliːtɪŋ/","lvl":"C1","ctx":"Academic","en":"Lasting for a very short time","vn":"Thoáng qua","m":"Fleeting -> Phờ lí: Cảm giác mệt mỏi chỉ thoáng qua","col1":"fleeting moment","vn1":"khoảnh khắc thoáng qua","ex1":"I caught a fleeting glimpse of him.","ex1v":"Tôi thoáng thấy anh ấy.","ex2":"A fleeting interest in the subject.","ex2v":"Một sự quan tâm thoáng qua đối với chủ đề này.","ex3":"A fleeting smile.","ex3v":"Một nụ cười thoáng qua.","fam":"fleet (v.)","syn":"brief","ant":"lasting"},
    {"w":"Perennial","pos":"adj.","ipa":"/pəˈreniəl/","lvl":"C2","ctx":"Academic","en":"Lasting or existing for a long or apparently infinite time","vn":"Sống lâu, tồn tại mãi mãi","m":"Perennial -> Bờ rên rỉ: Bờ sông rên rỉ mãi mãi vì sóng vỗ","col1":"perennial problem","vn1":"vấn đề muôn thuở","ex1":"It's a perennial favorite.","ex1v":"Đó là một sự yêu thích lâu dài.","ex2":"Lack of funding is a perennial problem.","ex2v":"Thiếu kinh phí là một vấn đề muôn thuở.","ex3":"Perennial flowers.","ex3v":"Hoa lâu năm.","fam":"perennially (adv.)","syn":"everlasting","ant":"temporary"},
    {"w":"Transient","pos":"adj.","ipa":"/ˈtrænziənt/","lvl":"C1","ctx":"Academic","en":"Lasting only for a short time; impermanent","vn":"Ngắn ngủi, nhất thời","m":"Transient -> Tranh tiền: Sự giàu có do tranh tiền chỉ là nhất thời","col1":"transient nature","vn1":"bản chất nhất thời","ex1":"The beauty of a rainbow is transient.","ex1v":"Vẻ đẹp của cầu vồng là nhất thời.","ex2":"A transient workforce.","ex2v":"Một lực lượng lao động tạm thời.","ex3":"Transient symptoms.","ex3v":"Triệu chứng thoáng qua.","fam":"transience (n.)","syn":"ephemeral","ant":"permanent"},
    {"w":"Anachronism","pos":"n.","ipa":"/əˈnækrənɪzəm/","lvl":"C2","ctx":"Academic","en":"A thing belonging to a period other than that in which it exists","vn":"Sự sai thời gian, sự lỗi thời","m":"Anachronism -> Ăn nặc: Ăn mặc sai thời gian, lỗi thời","col1":"historical anachronism","vn1":"sai lầm lịch sử về thời gian","ex1":"The sword is an anachronism in modern warfare.","ex1v":"Thanh kiếm là một thứ lỗi thời trong chiến tranh hiện đại.","ex2":"A film set in ancient Rome containing an anachronism.","ex2v":"Một bộ phim lấy bối cảnh La Mã cổ đại có chứa một chi tiết sai thời gian.","ex3":"He is a bit of an anachronism.","ex3v":"Anh ấy hơi lỗi thời.","fam":"anachronistic (adj.)","syn":"misplacement","ant":"N/A"},
    {"w":"Synchronous","pos":"adj.","ipa":"/ˈsɪŋkrənəs/","lvl":"C1","ctx":"Work","en":"Existing or occurring at the same time","vn":"Đồng bộ, cùng lúc","m":"Synchronous -> Xin cớ: Xin cớ để làm việc đồng bộ cùng nhau","col1":"synchronous learning","vn1":"học tập đồng bộ","ex1":"Synchronous movements of the dancers.","ex1v":"Chuyển động đồng bộ của các vũ công.","ex2":"Synchronous data transmission.","ex2v":"Truyền dữ liệu đồng bộ.","ex3":"A synchronous orbit.","ex3v":"Quỹ đạo đồng bộ.","fam":"synchronize (v.)","syn":"simultaneous","ant":"asynchronous"},
    {"w":"Concurrent","pos":"adj.","ipa":"/kənˈkʌrənt/","lvl":"C1","ctx":"Work","en":"Existing, happening, or done at the same time","vn":"Xảy ra đồng thời","m":"Concurrent -> Con cờ run: Con cờ run lên cùng lúc với ván đấu","col1":"concurrent sentences","vn1":"các bản án thi hành cùng lúc","ex1":"There are concurrent festivals in town.","ex1v":"Có các lễ hội diễn ra đồng thời trong thị trấn.","ex2":"Concurrent execution of programs.","ex2v":"Thực thi đồng thời các chương trình.","ex3":"He served three concurrent terms.","ex3v":"Ông phục vụ ba nhiệm kỳ cùng lúc.","fam":"concurrently (adv.)","syn":"simultaneous","ant":"sequential"},
    {"w":"Interim","pos":"n./adj.","ipa":"/ˈɪntərɪm/","lvl":"C1","ctx":"Work","en":"The intervening time; provisional or temporary","vn":"Tạm thời, khoảng thời gian chuyển tiếp","m":"Interim -> In tờ rơi: In tờ rơi tạm thời trong lúc chờ biển báo","col1":"in the interim","vn1":"trong khoảng thời gian đó","ex1":"An interim government was formed.","ex1v":"Một chính phủ lâm thời đã được thành lập.","ex2":"Interim financial reports.","ex2v":"Báo cáo tài chính giữa kỳ (tạm thời).","ex3":"He acted as CEO in the interim.","ex3v":"Ông đóng vai trò CEO trong thời gian chuyển tiếp.","fam":"N/A","syn":"provisional","ant":"permanent"},
    {"w":"Incessant","pos":"adj.","ipa":"/ɪnˈsesnt/","lvl":"C1","ctx":"Academic","en":"Continuing without pause or interruption","vn":"Không ngừng, liên miên","m":"Incessant -> In xé: In rồi xé liên miên không ngừng","col1":"incessant rain","vn1":"mưa liên miên","ex1":"The incessant noise kept me awake.","ex1v":"Tiếng ồn không ngừng khiến tôi thao thức.","ex2":"Incessant demands for improvement.","ex2v":"Nhu cầu cải tiến không ngừng.","ex3":"Incessant complaining.","ex3v":"Phàn nàn không ngừng.","fam":"incessantly (adv.)","syn":"ceaseless","ant":"intermittent"},
    {"w":"Sporadic","pos":"adj.","ipa":"/spəˈrædɪk/","lvl":"C1","ctx":"Academic","en":"Occurring at irregular intervals or only in a few places","vn":"Rải rác, thỉnh thoảng","m":"Sporadic -> Sợ ba đánh: Sợ ba đánh nên chỉ trốn rải rác vài chỗ","col1":"sporadic fighting","vn1":"giao tranh lẻ tẻ","ex1":"There were sporadic showers.","ex1v":"Có những trận mưa rào rải rác.","ex2":"Sporadic outbreaks of the disease.","ex2v":"Sự bùng phát lẻ tẻ của căn bệnh.","ex3":"A sporadic success.","ex3v":"Một thành công thi thoảng.","fam":"sporadically (adv.)","syn":"occasional","ant":"frequent"},
    {"w":"Intermittent","pos":"adj.","ipa":"/ˌɪntəˈmɪtənt/","lvl":"C1","ctx":"Work","en":"Occurring at irregular intervals; not continuous or steady","vn":"Gián đoạn, từng cơn","m":"Intermittent -> In tơ mịn: Máy in nhả tơ mịn từng đợt gián đoạn","col1":"intermittent fasting","vn1":"nhịn ăn gián đoạn","ex1":"Intermittent rain is expected.","ex1v":"Dự báo có mưa gián đoạn.","ex2":"Intermittent faults in the network.","ex2v":"Các lỗi gián đoạn trong mạng.","ex3":"An intermittent signal.","ex3v":"Tín hiệu ngắt quãng.","fam":"intermittently (adv.)","syn":"sporadic","ant":"continuous"},
    {"w":"Protracted","pos":"adj.","ipa":"/prəˈtræktɪd/","lvl":"C2","ctx":"Academic","en":"Lasting for a long time or longer than expected or usual","vn":"Kéo dài, dai dẳng","m":"Protracted -> Bờ rào rách: Tranh chấp bờ rào rách kéo dài","col1":"protracted negotiations","vn1":"các cuộc đàm phán kéo dài","ex1":"A protracted legal battle.","ex1v":"Một cuộc chiến pháp lý kéo dài.","ex2":"Protracted delays in the schedule.","ex2v":"Sự chậm trễ kéo dài trong lịch trình.","ex3":"A protracted illness.","ex3v":"Một căn bệnh dai dẳng.","fam":"protract (v.)","syn":"prolonged","ant":"brief"},
    {"w":"Epoch","pos":"n.","ipa":"/ˈiːpɒk/","lvl":"C2","ctx":"Academic","en":"A particular period of time in history or a person's life","vn":"Kỷ nguyên, thời đại","m":"Epoch -> Ép bọc: Kỷ nguyên mới người ta ép bọc mọi thứ","col1":"new epoch","vn1":"kỷ nguyên mới","ex1":"The Victorian epoch.","ex1v":"Kỷ nguyên Victoria.","ex2":"An epoch of great technological progress.","ex2v":"Một kỷ nguyên của tiến bộ công nghệ lớn.","ex3":"It marked the end of an epoch.","ex3v":"Nó đánh dấu sự kết thúc của một kỷ nguyên.","fam":"epochal (adj.)","syn":"era","ant":"N/A"},
    {"w":"Perpetuity","pos":"n.","ipa":"/ˌpɜːpəˈtjuːəti/","lvl":"C2","ctx":"Academic","en":"The state or quality of lasting forever","vn":"Sự vĩnh viễn, vô tận","m":"Perpetuity -> Bờ bến tuy: Bờ bến tuy xa nhưng sẽ tồn tại vĩnh viễn","col1":"in perpetuity","vn1":"vĩnh viễn","ex1":"The land was granted to them in perpetuity.","ex1v":"Mảnh đất được trao cho họ vĩnh viễn.","ex2":"A contract valid in perpetuity.","ex2v":"Một hợp đồng có giá trị vĩnh viễn.","ex3":"Banned in perpetuity.","ex3v":"Bị cấm vĩnh viễn.","fam":"perpetual (adj.)","syn":"eternity","ant":"N/A"}
]

template = """# {w}
*{pos}*
> {ipa}

---
**Level:** {lvl} | **Ngữ cảnh:** {ctx} | **Chủ đề:** TIME

## 📌 Ý nghĩa (Meaning)
- **[EN]:** {en}
- **[VN]:** {vn}

## 🧠 Mẹo nhớ (Mnemonics)
💡 {m}

## 🧩 Cụm từ thường đi kèm (Collocations)
- `{col1}`: {vn1}

## 🎬 Ví dụ thực tế (Real-world Examples)
1. 💬 *Daily:* {ex1}
   *-> {ex1v}*
2. 💼 *Work/Academic:* {ex2}
   *-> {ex2v}*
3. 🎬 *Media/Movie:* {ex3}
   *-> {ex3v}*

## 🕸️ Mạng lưới từ (Word Network)
**Word Family:**
- {fam}

**Synonyms:** {syn}
**Antonyms:** {ant}
"""

for item in words:
    file_path = os.path.join(target_dir, f"{item['w']}.md")
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(template.format(**item))

print(f"Successfully generated {len(words)} vocabulary files in {target_dir}.")
