import os

TARGET_DIR = "/home/thinh/Documents/Obsidian Vault/English/Vocabulary Topics/2. Daily Life & Habits/HOBBIES"
os.makedirs(TARGET_DIR, exist_ok=True)

WORDS = [
    {
        "word": "Fishing",
        "pos": "n",
        "ipa": "/ˈfɪʃɪŋ/",
        "lvl": "A1",
        "ctx": "Daily",
        "en": "The sport or job of catching fish.",
        "vn": "Câu cá, đánh cá.",
        "m": "Fishing là việc đi bắt (catch) những con cá (fish).",
        "col1": "go fishing",
        "vn1": "đi câu cá",
        "ex1": "We usually go fishing on Sundays.",
        "ex1v": "Chúng tôi thường đi câu cá vào Chủ nhật.",
        "ex2": "Commercial fishing is an important industry here.",
        "ex2v": "Đánh bắt cá thương mại là ngành công nghiệp quan trọng ở đây.",
        "ex3": "He learned about fishing from a documentary.",
        "ex3v": "Anh ấy học về việc câu cá từ một bộ phim tài liệu.",
        "fam": "fish (n, v), fisher (n), fisherman (n)",
        "syn": "angling",
        "ant": "None"
    },
    {
        "word": "Knit",
        "pos": "v",
        "ipa": "/nɪt/",
        "lvl": "B1",
        "ctx": "Daily",
        "en": "To make clothes, etc. from wool or cotton thread using two long needles.",
        "vn": "Đan (len, sợi).",
        "m": "Knit nghe như 'nịt', đan chặt như thắt nịt.",
        "col1": "knit a sweater",
        "vn1": "đan một chiếc áo len",
        "ex1": "My grandmother taught me how to knit.",
        "ex1v": "Bà tôi đã dạy tôi cách đan len.",
        "ex2": "She knits to relieve stress after work.",
        "ex2v": "Cô ấy đan len để giảm căng thẳng sau giờ làm việc.",
        "ex3": "In the movie, she was knitting by the fireplace.",
        "ex3v": "Trong phim, cô ấy đang đan len bên lò sưởi.",
        "fam": "knitting (n), knitter (n), knitted (adj)",
        "syn": "weave, interlace",
        "ant": "unravel"
    },
    {
        "word": "Paint",
        "pos": "v",
        "ipa": "/peɪnt/",
        "lvl": "A1",
        "ctx": "Daily",
        "en": "To make a picture of something or someone using paint.",
        "vn": "Sơn, vẽ (bằng sơn, màu nước).",
        "m": "Paint có âm 'p', giống như phết màu lên tường.",
        "col1": "paint a picture",
        "vn1": "vẽ một bức tranh",
        "ex1": "I like to paint in my free time.",
        "ex1v": "Tôi thích vẽ tranh vào thời gian rảnh.",
        "ex2": "They hired professionals to paint the office.",
        "ex2v": "Họ đã thuê thợ chuyên nghiệp để sơn văn phòng.",
        "ex3": "The artist is seen painting a masterpiece in the film.",
        "ex3v": "Người nghệ sĩ được thấy đang vẽ một kiệt tác trong phim.",
        "fam": "painting (n), painter (n), painted (adj)",
        "syn": "color, draw",
        "ant": "erase, strip"
    },
    {
        "word": "Hike",
        "pos": "v",
        "ipa": "/haɪk/",
        "lvl": "A2",
        "ctx": "Daily",
        "en": "To go for a long walk in the country, especially for pleasure.",
        "vn": "Đi bộ đường dài (leo núi).",
        "m": "Hike giống như chữ 'hái', đi lên núi để hái quả.",
        "col1": "go for a hike",
        "vn1": "đi bộ đường dài",
        "ex1": "We plan to hike in the mountains this weekend.",
        "ex1v": "Chúng tôi dự định đi bộ trên núi vào cuối tuần này.",
        "ex2": "The team building event included a nature hike.",
        "ex2v": "Sự kiện xây dựng đội ngũ bao gồm một chuyến đi bộ trong thiên nhiên.",
        "ex3": "The documentary showed them hiking the Appalachian Trail.",
        "ex3v": "Phim tài liệu chiếu cảnh họ đi bộ trên đường mòn Appalachian.",
        "fam": "hiking (n), hiker (n)",
        "syn": "trek, walk, ramble",
        "ant": "stay, rest"
    },
    {
        "word": "Swim",
        "pos": "v",
        "ipa": "/swɪm/",
        "lvl": "A1",
        "ctx": "Daily",
        "en": "To move through water by moving your arms and legs.",
        "vn": "Bơi lội.",
        "m": "Swim âm cuối 'im', khi bơi thì chìm trong nước mát.",
        "col1": "go swimming",
        "vn1": "đi bơi",
        "ex1": "I usually swim in the morning.",
        "ex1v": "Tôi thường bơi vào buổi sáng.",
        "ex2": "Swimming is considered an excellent cardiovascular workout.",
        "ex2v": "Bơi lội được coi là một bài tập tim mạch tuyệt vời.",
        "ex3": "The character learns to swim to escape the island.",
        "ex3v": "Nhân vật học bơi để thoát khỏi hòn đảo.",
        "fam": "swimming (n), swimmer (n)",
        "syn": "bathe, dip",
        "ant": "sink, drown"
    },
    {
        "word": "Cycle",
        "pos": "v",
        "ipa": "/ˈsaɪkl/",
        "lvl": "A2",
        "ctx": "Daily",
        "en": "To ride a bicycle.",
        "vn": "Đạp xe.",
        "m": "Cycle có âm giống vòng tuần hoàn, bánh xe quay tròn.",
        "col1": "cycle to work",
        "vn1": "đạp xe đi làm",
        "ex1": "I cycle to school every day.",
        "ex1v": "Tôi đạp xe đến trường mỗi ngày.",
        "ex2": "More people are cycling to reduce their carbon footprint.",
        "ex2v": "Ngày càng nhiều người đạp xe để giảm lượng khí thải carbon.",
        "ex3": "The opening scene shows kids cycling around the neighborhood.",
        "ex3v": "Cảnh mở đầu cho thấy lũ trẻ đạp xe quanh khu phố.",
        "fam": "cycling (n), cyclist (n), bicycle (n)",
        "syn": "bike, pedal",
        "ant": "drive, walk"
    },
    {
        "word": "Bake",
        "pos": "v",
        "ipa": "/beɪk/",
        "lvl": "A2",
        "ctx": "Daily",
        "en": "To cook food in an oven without extra fat or liquid.",
        "vn": "Nướng (bánh).",
        "m": "Bake có âm như 'bê', nướng bánh xong bưng bê ra.",
        "col1": "bake a cake",
        "vn1": "nướng một cái bánh",
        "ex1": "She loves to bake chocolate chip cookies.",
        "ex1v": "Cô ấy thích nướng bánh quy sô cô la hạt.",
        "ex2": "The culinary students learned to bake artisan bread.",
        "ex2v": "Sinh viên ẩm thực học cách nướng bánh mì thủ công.",
        "ex3": "The baking competition was a hit reality TV show.",
        "ex3v": "Cuộc thi làm bánh là một chương trình truyền hình thực tế ăn khách.",
        "fam": "baking (n), baker (n), bakery (n)",
        "syn": "roast, cook",
        "ant": "fry, boil"
    },
    {
        "word": "Garden",
        "pos": "v",
        "ipa": "/ˈɡɑːrdn/",
        "lvl": "B1",
        "ctx": "Daily",
        "en": "To work in a garden, growing plants, flowers, or vegetables.",
        "vn": "Làm vườn.",
        "m": "Garden đọc là 'ga-đần', gần với làm ngoài sân (garden).",
        "col1": "do some gardening",
        "vn1": "làm một chút công việc làm vườn",
        "ex1": "My mother gardens every weekend.",
        "ex1v": "Mẹ tôi làm vườn mỗi cuối tuần.",
        "ex2": "Urban gardening is becoming popular among city dwellers.",
        "ex2v": "Làm vườn đô thị đang trở nên phổ biến đối với cư dân thành phố.",
        "ex3": "The old man in the movie gardens to remember his wife.",
        "ex3v": "Ông già trong phim làm vườn để tưởng nhớ người vợ.",
        "fam": "garden (n), gardening (n), gardener (n)",
        "syn": "cultivate, plant",
        "ant": "neglect, destroy"
    },
    {
        "word": "Camp",
        "pos": "v",
        "ipa": "/kæmp/",
        "lvl": "A2",
        "ctx": "Daily",
        "en": "To set up a tent and stay in it, usually for a holiday.",
        "vn": "Cắm trại.",
        "m": "Camp giống như 'cắm', cắm lều để cắm trại.",
        "col1": "go camping",
        "vn1": "đi cắm trại",
        "ex1": "We are planning to camp near the lake.",
        "ex1v": "Chúng tôi dự định cắm trại gần hồ.",
        "ex2": "The research team had to camp in the jungle for a month.",
        "ex2v": "Nhóm nghiên cứu phải cắm trại trong rừng một tháng.",
        "ex3": "A scary movie about friends camping in the woods.",
        "ex3v": "Một bộ phim đáng sợ về những người bạn cắm trại trong rừng.",
        "fam": "camping (n), camper (n), campsite (n)",
        "syn": "bivouac, pitch a tent",
        "ant": "lodge, stay at a hotel"
    },
    {
        "word": "Surf",
        "pos": "v",
        "ipa": "/sɜːrf/",
        "lvl": "A2",
        "ctx": "Daily",
        "en": "To ride on a wave towards the shore while standing or lying on a surfboard.",
        "vn": "Lướt sóng, lướt web.",
        "m": "Surf như 'sợt', trượt trên mặt nước (hay trên web).",
        "col1": "go surfing",
        "vn1": "đi lướt sóng",
        "ex1": "They like to surf in California.",
        "ex1v": "Họ thích lướt sóng ở California.",
        "ex2": "He surfs the internet for academic research.",
        "ex2v": "Anh ấy lướt internet để nghiên cứu học thuật.",
        "ex3": "The documentary followed professional surfers around the world.",
        "ex3v": "Bộ phim tài liệu theo chân những người lướt sóng chuyên nghiệp vòng quanh thế giới.",
        "fam": "surfing (n), surfer (n), surfboard (n)",
        "syn": "ride waves, browse",
        "ant": "None"
    },
    {
        "word": "Sketch",
        "pos": "v",
        "ipa": "/sketʃ/",
        "lvl": "B1",
        "ctx": "Daily",
        "en": "To make a quick, rough drawing of something.",
        "vn": "Phác thảo, vẽ phác.",
        "m": "Sketch giống 'kết', vẽ phác kết cấu nhanh.",
        "col1": "sketch out a plan",
        "vn1": "phác thảo một kế hoạch",
        "ex1": "He likes to sketch people on the bus.",
        "ex1v": "Anh ấy thích phác họa mọi người trên xe buýt.",
        "ex2": "The architect sketched a rough design of the building.",
        "ex2v": "Kiến trúc sư đã phác thảo một thiết kế thô của tòa nhà.",
        "ex3": "Jack sketched Rose in the movie Titanic.",
        "ex3v": "Jack đã vẽ phác họa Rose trong bộ phim Titanic.",
        "fam": "sketch (n), sketchy (adj), sketchbook (n)",
        "syn": "draw, outline, draft",
        "ant": "detail, finish"
    },
    {
        "word": "Read",
        "pos": "v",
        "ipa": "/riːd/",
        "lvl": "A1",
        "ctx": "Daily",
        "en": "To look at and understand the meaning of written or printed words or symbols.",
        "vn": "Đọc.",
        "m": "Read như 'rít', rít sách đọc say sưa.",
        "col1": "read a book",
        "vn1": "đọc một cuốn sách",
        "ex1": "I try to read a few pages before bed.",
        "ex1v": "Tôi cố gắng đọc vài trang trước khi ngủ.",
        "ex2": "Students are required to read three articles per week.",
        "ex2v": "Sinh viên được yêu cầu đọc ba bài báo mỗi tuần.",
        "ex3": "She was seen reading a novel in the cafe.",
        "ex3v": "Cô ấy được thấy đang đọc tiểu thuyết trong quán cà phê.",
        "fam": "reading (n), reader (n), readable (adj)",
        "syn": "peruse, study",
        "ant": "write"
    },
    {
        "word": "Cook",
        "pos": "v",
        "ipa": "/kʊk/",
        "lvl": "A1",
        "ctx": "Daily",
        "en": "To prepare food and heat it so that it is ready to eat.",
        "vn": "Nấu ăn.",
        "m": "Cook âm 'cúc', cúc cu nấu ăn vui vẻ.",
        "col1": "cook dinner",
        "vn1": "nấu bữa tối",
        "ex1": "My dad usually cooks on weekends.",
        "ex1v": "Bố tôi thường nấu ăn vào cuối tuần.",
        "ex2": "The chef cooks using advanced culinary techniques.",
        "ex2v": "Đầu bếp nấu ăn bằng các kỹ thuật ẩm thực tiên tiến.",
        "ex3": "They cooked a feast in the movie Ratatouille.",
        "ex3v": "Họ đã nấu một bữa tiệc trong phim Ratatouille.",
        "fam": "cooking (n), cook (n), cooker (n), cookbook (n)",
        "syn": "prepare, bake, boil",
        "ant": "eat, consume"
    },
    {
        "word": "Sail",
        "pos": "v",
        "ipa": "/seɪl/",
        "lvl": "A2",
        "ctx": "Daily",
        "en": "To travel on water in a ship or boat.",
        "vn": "Chèo thuyền, đi thuyền, lái thuyền buồm.",
        "m": "Sail giống 'seo', căng buồm đón gió seo (sale).",
        "col1": "go sailing",
        "vn1": "đi thuyền buồm",
        "ex1": "We want to sail around the bay.",
        "ex1v": "Chúng tôi muốn đi thuyền quanh vịnh.",
        "ex2": "The team learned to sail as part of their leadership training.",
        "ex2v": "Đội ngũ đã học chèo thuyền như một phần của khóa huấn luyện lãnh đạo.",
        "ex3": "The pirates sail the seas in search of treasure.",
        "ex3v": "Bọn cướp biển giong buồm trên biển để tìm kho báu.",
        "fam": "sailing (n), sailor (n), sailboat (n)",
        "syn": "cruise, navigate",
        "ant": "dock, land"
    },
    {
        "word": "Jog",
        "pos": "v",
        "ipa": "/dʒɑːɡ/",
        "lvl": "A2",
        "ctx": "Daily",
        "en": "To run at a slow, steady pace, especially as a form of exercise.",
        "vn": "Chạy bộ (chạy chậm).",
        "m": "Jog đọc như 'dốc', chạy bộ lên dốc.",
        "col1": "go for a jog",
        "vn1": "đi chạy bộ",
        "ex1": "I jog in the park every morning.",
        "ex1v": "Tôi chạy bộ trong công viên mỗi sáng.",
        "ex2": "Jogging is recommended to improve cardiovascular health.",
        "ex2v": "Chạy bộ được khuyên dùng để cải thiện sức khỏe tim mạch.",
        "ex3": "The protagonist was jogging when he discovered the mystery.",
        "ex3v": "Nhân vật chính đang chạy bộ thì phát hiện ra bí ẩn.",
        "fam": "jogging (n), jogger (n)",
        "syn": "trot, run",
        "ant": "sprint, walk"
    },
    {
        "word": "Dance",
        "pos": "v",
        "ipa": "/dæns/",
        "lvl": "A1",
        "ctx": "Daily",
        "en": "To move your body to music.",
        "vn": "Khiêu vũ, nhảy múa.",
        "m": "Dance quen thuộc như từ 'đen', nhảy trong bóng đêm.",
        "col1": "dance to the music",
        "vn1": "nhảy theo nhạc",
        "ex1": "They like to dance at parties.",
        "ex1v": "Họ thích khiêu vũ ở các bữa tiệc.",
        "ex2": "She studies dance at the conservatory.",
        "ex2v": "Cô ấy học múa tại nhạc viện.",
        "ex3": "The final scene features everyone dancing together.",
        "ex3v": "Cảnh cuối cùng có tất cả mọi người cùng nhảy múa.",
        "fam": "dancer (n), dancing (n)",
        "syn": "groove, waltz, bop",
        "ant": "stand still"
    },
    {
        "word": "Sing",
        "pos": "v",
        "ipa": "/sɪŋ/",
        "lvl": "A1",
        "ctx": "Daily",
        "en": "To make musical sounds with your voice.",
        "vn": "Hát.",
        "m": "Sing phát âm là 'sing', ca hát thì sinh động.",
        "col1": "sing a song",
        "vn1": "hát một bài hát",
        "ex1": "She likes to sing in the shower.",
        "ex1v": "Cô ấy thích hát trong lúc tắm.",
        "ex2": "The choir will sing at the graduation ceremony.",
        "ex2v": "Dàn hợp xướng sẽ hát tại lễ tốt nghiệp.",
        "ex3": "He sings a romantic song to her in the musical.",
        "ex3v": "Anh ấy hát một bài hát lãng mạn cho cô ấy trong vở nhạc kịch.",
        "fam": "singer (n), singing (n), song (n)",
        "syn": "vocalize, chant",
        "ant": "keep silent"
    },
    {
        "word": "Craft",
        "pos": "v",
        "ipa": "/kræft/",
        "lvl": "B1",
        "ctx": "Daily",
        "en": "To make objects, especially in a skilled way.",
        "vn": "Làm đồ thủ công, chế tác.",
        "m": "Craft như 'cáp', tạo ra các vật phẩm thủ công.",
        "col1": "craft a masterpiece",
        "vn1": "chế tác một kiệt tác",
        "ex1": "He likes to craft wooden toys for his kids.",
        "ex1v": "Anh ấy thích làm đồ chơi bằng gỗ cho con cái.",
        "ex2": "The author carefully crafted the narrative of the novel.",
        "ex2v": "Tác giả đã cẩn thận nhào nặn câu chuyện của cuốn tiểu thuyết.",
        "ex3": "In the game, you can craft various weapons.",
        "ex3v": "Trong trò chơi, bạn có thể chế tạo các loại vũ khí khác nhau.",
        "fam": "craft (n), craftsman (n), craftsmanship (n), crafty (adj)",
        "syn": "make, create, fashion",
        "ant": "destroy, dismantle"
    },
    {
        "word": "Ski",
        "pos": "v",
        "ipa": "/skiː/",
        "lvl": "A2",
        "ctx": "Daily",
        "en": "To move over snow on skis.",
        "vn": "Trượt tuyết.",
        "m": "Ski âm 'ki', như ván trượt kì diệu trên tuyết.",
        "col1": "go skiing",
        "vn1": "đi trượt tuyết",
        "ex1": "We are planning to ski in the Alps this winter.",
        "ex1v": "Chúng tôi dự định trượt tuyết ở dãy Alps vào mùa đông này.",
        "ex2": "Professional skiing requires intense physical training.",
        "ex2v": "Trượt tuyết chuyên nghiệp đòi hỏi sự rèn luyện thể chất cường độ cao.",
        "ex3": "James Bond skis away from the villains in the movie.",
        "ex3v": "James Bond trượt tuyết tẩu thoát khỏi bọn phản diện trong phim.",
        "fam": "skiing (n), skier (n)",
        "syn": "glide, slide",
        "ant": "None"
    },
    {
        "word": "Sew",
        "pos": "v",
        "ipa": "/soʊ/",
        "lvl": "B1",
        "ctx": "Daily",
        "en": "To use a needle and thread to make stitches in cloth.",
        "vn": "Khâu, may vá.",
        "m": "Sew đọc như 'sô', sâu kim vào để khâu.",
        "col1": "sew a button on",
        "vn1": "đơm một cái cúc áo",
        "ex1": "My grandmother taught me how to sew.",
        "ex1v": "Bà tôi đã dạy tôi cách khâu vá.",
        "ex2": "The tailor sewed the custom suit perfectly.",
        "ex2v": "Người thợ may đã khâu bộ vest may đo một cách hoàn hảo.",
        "ex3": "She is seen sewing a dress for the ball in the fairy tale.",
        "ex3v": "Cô ấy được thấy đang may một chiếc váy cho buổi dạ hội trong truyện cổ tích.",
        "fam": "sewing (n), sewer (n)",
        "syn": "stitch, mend",
        "ant": "tear, rip"
    }
]

TEMPLATE = """# {word}
*{pos}*
> {ipa}

---
**Level:** {lvl} | **Ngữ cảnh:** {ctx} | **Chủ đề:** HOBBIES

## 📌 Ý nghĩa (Meaning)
- **[EN]:** {en}
- **[VN]:** {vn}

## 🧠 Mẹo nhớ (Mnemonics)
💡 {m}

## 🧩 Cụm từ thường đi kèm (Collocations)
- `{col1}`: {vn1}

## 🎬 Ví dụ thực tế (Real-world Examples)
1. 💬 *Daily:* {ex1}
   *-> {ex1v}*
2. 💼 *Work/Academic:* {ex2}
   *-> {ex2v}*
3. 🎬 *Media/Movie:* {ex3}
   *-> {ex3v}*

## 🕸️ Mạng lưới từ (Word Network)
**Word Family:**
- {fam}

**Synonyms:** {syn}
**Antonyms:** {ant}
"""

for w in WORDS:
    file_path = os.path.join(TARGET_DIR, f"{w['word']}.md")
    content = TEMPLATE.format(**w)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

print("Vocabulary files created successfully!")
